-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor_24regs\monitor_24regs_dut.vhd
-- Created: 2025-02-28 23:11:54
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: monitor_24regs_dut
-- Source Path: monitor_24regs/monitor_24regs_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY monitor_24regs_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        dataWriteAXI0                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI1                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI2                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI3                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI4                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI5                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI6                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI7                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead9                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead10                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead11                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead12                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead13                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead14                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead15                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI8                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI9                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI10                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI11                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI12                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI13                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI14                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI15                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI16                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI17                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI18                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI19                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI20                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI21                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI22                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI23                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead16                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead17                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead18                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead19                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead20                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead21                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead22                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead23                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        dataWrite0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite4                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite5                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite6                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite7                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite8                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite9                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite10                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite11                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite12                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite13                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite14                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite15                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI8                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI9                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI10                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI11                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI12                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI13                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI14                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI15                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite16                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite17                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite18                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite19                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite20                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite21                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite22                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite23                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI16                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI17                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI18                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI19                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI20                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI21                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI22                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI23                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END monitor_24regs_dut;


ARCHITECTURE rtl OF monitor_24regs_dut IS

  -- Component Declarations
  COMPONENT monitor_24regs_src_monitor_24regs_dut
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataWriteAXI0                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI1                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI2                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI3                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI4                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI5                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI6                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI7                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead0                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead8                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead9                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead10                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead11                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead12                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead13                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead14                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead15                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI8                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI9                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI10                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI11                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI12                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI13                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI14                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI15                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI16                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI17                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI18                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI19                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI20                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI21                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI22                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI23                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead16                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead17                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead18                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead19                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead20                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead21                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead22                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead23                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          dataWrite0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI0                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI1                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI2                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI3                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI4                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI5                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI6                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI7                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite8                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite9                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite10                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite11                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite12                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite13                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite14                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite15                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI8                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI9                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI10                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI11                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI12                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI13                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI14                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI15                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite16                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite17                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite18                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite19                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite20                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite21                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite22                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite23                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI16                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI17                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI18                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI19                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI20                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI21                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI22                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI23                   :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : monitor_24regs_src_monitor_24regs_dut
    USE ENTITY work.monitor_24regs_src_monitor_24regs_dut(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL dataWrite0_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite1_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite2_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite3_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite4_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite5_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite6_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite7_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI0_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI1_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI2_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI3_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI4_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI5_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI6_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI7_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite8_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite9_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite10_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite11_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite12_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite13_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite14_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite15_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI8_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI9_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI10_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI11_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI12_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI13_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI14_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI15_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite16_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite17_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite18_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite19_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite20_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite21_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite22_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite23_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI16_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI17_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI18_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI19_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI20_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI21_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI22_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI23_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_monitor_24regs_src_monitor_24regs_dut : monitor_24regs_src_monitor_24regs_dut
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              dataWriteAXI0 => dataWriteAXI0,  -- ufix32
              dataWriteAXI1 => dataWriteAXI1,  -- ufix32
              dataWriteAXI2 => dataWriteAXI2,  -- ufix32
              dataWriteAXI3 => dataWriteAXI3,  -- ufix32
              dataWriteAXI4 => dataWriteAXI4,  -- ufix32
              dataWriteAXI5 => dataWriteAXI5,  -- ufix32
              dataWriteAXI6 => dataWriteAXI6,  -- ufix32
              dataWriteAXI7 => dataWriteAXI7,  -- ufix32
              dataRead0 => dataRead0,  -- ufix32
              dataRead1 => dataRead1,  -- ufix32
              dataRead2 => dataRead2,  -- ufix32
              dataRead3 => dataRead3,  -- ufix32
              dataRead4 => dataRead4,  -- ufix32
              dataRead5 => dataRead5,  -- ufix32
              dataRead6 => dataRead6,  -- ufix32
              dataRead7 => dataRead7,  -- ufix32
              dataRead8 => dataRead8,  -- ufix32
              dataRead9 => dataRead9,  -- ufix32
              dataRead10 => dataRead10,  -- ufix32
              dataRead11 => dataRead11,  -- ufix32
              dataRead12 => dataRead12,  -- ufix32
              dataRead13 => dataRead13,  -- ufix32
              dataRead14 => dataRead14,  -- ufix32
              dataRead15 => dataRead15,  -- ufix32
              dataWriteAXI8 => dataWriteAXI8,  -- ufix32
              dataWriteAXI9 => dataWriteAXI9,  -- ufix32
              dataWriteAXI10 => dataWriteAXI10,  -- ufix32
              dataWriteAXI11 => dataWriteAXI11,  -- ufix32
              dataWriteAXI12 => dataWriteAXI12,  -- ufix32
              dataWriteAXI13 => dataWriteAXI13,  -- ufix32
              dataWriteAXI14 => dataWriteAXI14,  -- ufix32
              dataWriteAXI15 => dataWriteAXI15,  -- ufix32
              dataWriteAXI16 => dataWriteAXI16,  -- ufix32
              dataWriteAXI17 => dataWriteAXI17,  -- ufix32
              dataWriteAXI18 => dataWriteAXI18,  -- ufix32
              dataWriteAXI19 => dataWriteAXI19,  -- ufix32
              dataWriteAXI20 => dataWriteAXI20,  -- ufix32
              dataWriteAXI21 => dataWriteAXI21,  -- ufix32
              dataWriteAXI22 => dataWriteAXI22,  -- ufix32
              dataWriteAXI23 => dataWriteAXI23,  -- ufix32
              dataRead16 => dataRead16,  -- ufix32
              dataRead17 => dataRead17,  -- ufix32
              dataRead18 => dataRead18,  -- ufix32
              dataRead19 => dataRead19,  -- ufix32
              dataRead20 => dataRead20,  -- ufix32
              dataRead21 => dataRead21,  -- ufix32
              dataRead22 => dataRead22,  -- ufix32
              dataRead23 => dataRead23,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              dataWrite0 => dataWrite0_sig,  -- ufix32
              dataWrite1 => dataWrite1_sig,  -- ufix32
              dataWrite2 => dataWrite2_sig,  -- ufix32
              dataWrite3 => dataWrite3_sig,  -- ufix32
              dataWrite4 => dataWrite4_sig,  -- ufix32
              dataWrite5 => dataWrite5_sig,  -- ufix32
              dataWrite6 => dataWrite6_sig,  -- ufix32
              dataWrite7 => dataWrite7_sig,  -- ufix32
              dataReadAXI0 => dataReadAXI0_sig,  -- ufix32
              dataReadAXI1 => dataReadAXI1_sig,  -- ufix32
              dataReadAXI2 => dataReadAXI2_sig,  -- ufix32
              dataReadAXI3 => dataReadAXI3_sig,  -- ufix32
              dataReadAXI4 => dataReadAXI4_sig,  -- ufix32
              dataReadAXI5 => dataReadAXI5_sig,  -- ufix32
              dataReadAXI6 => dataReadAXI6_sig,  -- ufix32
              dataReadAXI7 => dataReadAXI7_sig,  -- ufix32
              dataWrite8 => dataWrite8_sig,  -- ufix32
              dataWrite9 => dataWrite9_sig,  -- ufix32
              dataWrite10 => dataWrite10_sig,  -- ufix32
              dataWrite11 => dataWrite11_sig,  -- ufix32
              dataWrite12 => dataWrite12_sig,  -- ufix32
              dataWrite13 => dataWrite13_sig,  -- ufix32
              dataWrite14 => dataWrite14_sig,  -- ufix32
              dataWrite15 => dataWrite15_sig,  -- ufix32
              dataReadAXI8 => dataReadAXI8_sig,  -- ufix32
              dataReadAXI9 => dataReadAXI9_sig,  -- ufix32
              dataReadAXI10 => dataReadAXI10_sig,  -- ufix32
              dataReadAXI11 => dataReadAXI11_sig,  -- ufix32
              dataReadAXI12 => dataReadAXI12_sig,  -- ufix32
              dataReadAXI13 => dataReadAXI13_sig,  -- ufix32
              dataReadAXI14 => dataReadAXI14_sig,  -- ufix32
              dataReadAXI15 => dataReadAXI15_sig,  -- ufix32
              dataWrite16 => dataWrite16_sig,  -- ufix32
              dataWrite17 => dataWrite17_sig,  -- ufix32
              dataWrite18 => dataWrite18_sig,  -- ufix32
              dataWrite19 => dataWrite19_sig,  -- ufix32
              dataWrite20 => dataWrite20_sig,  -- ufix32
              dataWrite21 => dataWrite21_sig,  -- ufix32
              dataWrite22 => dataWrite22_sig,  -- ufix32
              dataWrite23 => dataWrite23_sig,  -- ufix32
              dataReadAXI16 => dataReadAXI16_sig,  -- ufix32
              dataReadAXI17 => dataReadAXI17_sig,  -- ufix32
              dataReadAXI18 => dataReadAXI18_sig,  -- ufix32
              dataReadAXI19 => dataReadAXI19_sig,  -- ufix32
              dataReadAXI20 => dataReadAXI20_sig,  -- ufix32
              dataReadAXI21 => dataReadAXI21_sig,  -- ufix32
              dataReadAXI22 => dataReadAXI22_sig,  -- ufix32
              dataReadAXI23 => dataReadAXI23_sig  -- ufix32
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  dataWrite0 <= dataWrite0_sig;

  dataWrite1 <= dataWrite1_sig;

  dataWrite2 <= dataWrite2_sig;

  dataWrite3 <= dataWrite3_sig;

  dataWrite4 <= dataWrite4_sig;

  dataWrite5 <= dataWrite5_sig;

  dataWrite6 <= dataWrite6_sig;

  dataWrite7 <= dataWrite7_sig;

  dataReadAXI0 <= dataReadAXI0_sig;

  dataReadAXI1 <= dataReadAXI1_sig;

  dataReadAXI2 <= dataReadAXI2_sig;

  dataReadAXI3 <= dataReadAXI3_sig;

  dataReadAXI4 <= dataReadAXI4_sig;

  dataReadAXI5 <= dataReadAXI5_sig;

  dataReadAXI6 <= dataReadAXI6_sig;

  dataReadAXI7 <= dataReadAXI7_sig;

  dataWrite8 <= dataWrite8_sig;

  dataWrite9 <= dataWrite9_sig;

  dataWrite10 <= dataWrite10_sig;

  dataWrite11 <= dataWrite11_sig;

  dataWrite12 <= dataWrite12_sig;

  dataWrite13 <= dataWrite13_sig;

  dataWrite14 <= dataWrite14_sig;

  dataWrite15 <= dataWrite15_sig;

  dataReadAXI8 <= dataReadAXI8_sig;

  dataReadAXI9 <= dataReadAXI9_sig;

  dataReadAXI10 <= dataReadAXI10_sig;

  dataReadAXI11 <= dataReadAXI11_sig;

  dataReadAXI12 <= dataReadAXI12_sig;

  dataReadAXI13 <= dataReadAXI13_sig;

  dataReadAXI14 <= dataReadAXI14_sig;

  dataReadAXI15 <= dataReadAXI15_sig;

  dataWrite16 <= dataWrite16_sig;

  dataWrite17 <= dataWrite17_sig;

  dataWrite18 <= dataWrite18_sig;

  dataWrite19 <= dataWrite19_sig;

  dataWrite20 <= dataWrite20_sig;

  dataWrite21 <= dataWrite21_sig;

  dataWrite22 <= dataWrite22_sig;

  dataWrite23 <= dataWrite23_sig;

  dataReadAXI16 <= dataReadAXI16_sig;

  dataReadAXI17 <= dataReadAXI17_sig;

  dataReadAXI18 <= dataReadAXI18_sig;

  dataReadAXI19 <= dataReadAXI19_sig;

  dataReadAXI20 <= dataReadAXI20_sig;

  dataReadAXI21 <= dataReadAXI21_sig;

  dataReadAXI22 <= dataReadAXI22_sig;

  dataReadAXI23 <= dataReadAXI23_sig;

END rtl;

