-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor_24regs\monitor_24regs_src_monitor_24regs_dut.vhd
-- Created: 2025-02-28 23:11:43
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- dataWrite0                    ce_out        1
-- dataWrite1                    ce_out        1
-- dataWrite2                    ce_out        1
-- dataWrite3                    ce_out        1
-- dataWrite4                    ce_out        1
-- dataWrite5                    ce_out        1
-- dataWrite6                    ce_out        1
-- dataWrite7                    ce_out        1
-- dataReadAXI0                  ce_out        1
-- dataReadAXI1                  ce_out        1
-- dataReadAXI2                  ce_out        1
-- dataReadAXI3                  ce_out        1
-- dataReadAXI4                  ce_out        1
-- dataReadAXI5                  ce_out        1
-- dataReadAXI6                  ce_out        1
-- dataReadAXI7                  ce_out        1
-- dataWrite8                    ce_out        1
-- dataWrite9                    ce_out        1
-- dataWrite10                   ce_out        1
-- dataWrite11                   ce_out        1
-- dataWrite12                   ce_out        1
-- dataWrite13                   ce_out        1
-- dataWrite14                   ce_out        1
-- dataWrite15                   ce_out        1
-- dataReadAXI8                  ce_out        1
-- dataReadAXI9                  ce_out        1
-- dataReadAXI10                 ce_out        1
-- dataReadAXI11                 ce_out        1
-- dataReadAXI12                 ce_out        1
-- dataReadAXI13                 ce_out        1
-- dataReadAXI14                 ce_out        1
-- dataReadAXI15                 ce_out        1
-- dataWrite16                   ce_out        1
-- dataWrite17                   ce_out        1
-- dataWrite18                   ce_out        1
-- dataWrite19                   ce_out        1
-- dataWrite20                   ce_out        1
-- dataWrite21                   ce_out        1
-- dataWrite22                   ce_out        1
-- dataWrite23                   ce_out        1
-- dataReadAXI16                 ce_out        1
-- dataReadAXI17                 ce_out        1
-- dataReadAXI18                 ce_out        1
-- dataReadAXI19                 ce_out        1
-- dataReadAXI20                 ce_out        1
-- dataReadAXI21                 ce_out        1
-- dataReadAXI22                 ce_out        1
-- dataReadAXI23                 ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: monitor_24regs_src_monitor_24regs_dut
-- Source Path: monitor_24regs/monitor_24regs_dut
-- Hierarchy Level: 0
-- Model version: 5.18
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY monitor_24regs_src_monitor_24regs_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        dataWriteAXI0                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI1                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI2                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI3                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI4                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI5                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI6                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI7                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead9                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead10                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead11                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead12                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead13                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead14                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead15                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI8                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI9                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI10                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI11                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI12                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI13                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI14                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI15                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI16                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI17                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI18                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI19                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI20                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI21                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI22                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI23                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead16                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead17                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead18                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead19                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead20                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead21                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead22                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead23                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ce_out                            :   OUT   std_logic;
        dataWrite0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite4                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite5                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite6                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite7                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite8                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite9                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite10                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite11                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite12                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite13                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite14                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite15                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI8                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI9                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI10                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI11                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI12                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI13                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI14                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI15                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite16                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite17                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite18                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite19                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite20                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite21                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite22                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite23                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI16                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI17                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI18                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI19                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI20                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI21                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI22                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI23                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END monitor_24regs_src_monitor_24regs_dut;


ARCHITECTURE rtl OF monitor_24regs_src_monitor_24regs_dut IS

  -- Component Declarations
  COMPONENT monitor_24regs_src_MATLAB_Function
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataWriteAXI0                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI1                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI2                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI3                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI4                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI5                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI6                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI7                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI8                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI9                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI10                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI11                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI12                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI13                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI14                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI15                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI16                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI17                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI18                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI19                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI20                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI21                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI22                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI23                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead0                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead8                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead9                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead10                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead11                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead12                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead13                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead14                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead15                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead16                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead17                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead18                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead19                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead20                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead21                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead22                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead23                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite8                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite9                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite10                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite11                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite12                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite13                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite14                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite15                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite16                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite17                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite18                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite19                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite20                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite21                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite22                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite23                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI0                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI1                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI2                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI3                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI4                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI5                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI6                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI7                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI8                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI9                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI10                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI11                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI12                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI13                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI14                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI15                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI16                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI17                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI18                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI19                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI20                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI21                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI22                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI23                   :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : monitor_24regs_src_MATLAB_Function
    USE ENTITY work.monitor_24regs_src_MATLAB_Function(rtl);

  -- Signals
  SIGNAL dataWrite0_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite1_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite2_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite3_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite4_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite5_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite6_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite7_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite8_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite9_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite10_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite11_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite12_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite13_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite14_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite15_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite16_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite17_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite18_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite19_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite20_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite21_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite22_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite23_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI0_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI1_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI2_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI3_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI4_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI5_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI6_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI7_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI8_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI9_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI10_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI11_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI12_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI13_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI14_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI15_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI16_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI17_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI18_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI19_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI20_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI21_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI22_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI23_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_MATLAB_Function : monitor_24regs_src_MATLAB_Function
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataWriteAXI0 => dataWriteAXI0,  -- uint32
              dataWriteAXI1 => dataWriteAXI1,  -- uint32
              dataWriteAXI2 => dataWriteAXI2,  -- uint32
              dataWriteAXI3 => dataWriteAXI3,  -- uint32
              dataWriteAXI4 => dataWriteAXI4,  -- uint32
              dataWriteAXI5 => dataWriteAXI5,  -- uint32
              dataWriteAXI6 => dataWriteAXI6,  -- uint32
              dataWriteAXI7 => dataWriteAXI7,  -- uint32
              dataWriteAXI8 => dataWriteAXI8,  -- uint32
              dataWriteAXI9 => dataWriteAXI9,  -- uint32
              dataWriteAXI10 => dataWriteAXI10,  -- uint32
              dataWriteAXI11 => dataWriteAXI11,  -- uint32
              dataWriteAXI12 => dataWriteAXI12,  -- uint32
              dataWriteAXI13 => dataWriteAXI13,  -- uint32
              dataWriteAXI14 => dataWriteAXI14,  -- uint32
              dataWriteAXI15 => dataWriteAXI15,  -- uint32
              dataWriteAXI16 => dataWriteAXI16,  -- uint32
              dataWriteAXI17 => dataWriteAXI17,  -- uint32
              dataWriteAXI18 => dataWriteAXI18,  -- uint32
              dataWriteAXI19 => dataWriteAXI19,  -- uint32
              dataWriteAXI20 => dataWriteAXI20,  -- uint32
              dataWriteAXI21 => dataWriteAXI21,  -- uint32
              dataWriteAXI22 => dataWriteAXI22,  -- uint32
              dataWriteAXI23 => dataWriteAXI23,  -- uint32
              dataRead0 => dataRead0,  -- uint32
              dataRead1 => dataRead1,  -- uint32
              dataRead2 => dataRead2,  -- uint32
              dataRead3 => dataRead3,  -- uint32
              dataRead4 => dataRead4,  -- uint32
              dataRead5 => dataRead5,  -- uint32
              dataRead6 => dataRead6,  -- uint32
              dataRead7 => dataRead7,  -- uint32
              dataRead8 => dataRead8,  -- uint32
              dataRead9 => dataRead9,  -- uint32
              dataRead10 => dataRead10,  -- uint32
              dataRead11 => dataRead11,  -- uint32
              dataRead12 => dataRead12,  -- uint32
              dataRead13 => dataRead13,  -- uint32
              dataRead14 => dataRead14,  -- uint32
              dataRead15 => dataRead15,  -- uint32
              dataRead16 => dataRead16,  -- uint32
              dataRead17 => dataRead17,  -- uint32
              dataRead18 => dataRead18,  -- uint32
              dataRead19 => dataRead19,  -- uint32
              dataRead20 => dataRead20,  -- uint32
              dataRead21 => dataRead21,  -- uint32
              dataRead22 => dataRead22,  -- uint32
              dataRead23 => dataRead23,  -- uint32
              dataWrite0 => dataWrite0_tmp,  -- uint32
              dataWrite1 => dataWrite1_tmp,  -- uint32
              dataWrite2 => dataWrite2_tmp,  -- uint32
              dataWrite3 => dataWrite3_tmp,  -- uint32
              dataWrite4 => dataWrite4_tmp,  -- uint32
              dataWrite5 => dataWrite5_tmp,  -- uint32
              dataWrite6 => dataWrite6_tmp,  -- uint32
              dataWrite7 => dataWrite7_tmp,  -- uint32
              dataWrite8 => dataWrite8_tmp,  -- uint32
              dataWrite9 => dataWrite9_tmp,  -- uint32
              dataWrite10 => dataWrite10_tmp,  -- uint32
              dataWrite11 => dataWrite11_tmp,  -- uint32
              dataWrite12 => dataWrite12_tmp,  -- uint32
              dataWrite13 => dataWrite13_tmp,  -- uint32
              dataWrite14 => dataWrite14_tmp,  -- uint32
              dataWrite15 => dataWrite15_tmp,  -- uint32
              dataWrite16 => dataWrite16_tmp,  -- uint32
              dataWrite17 => dataWrite17_tmp,  -- uint32
              dataWrite18 => dataWrite18_tmp,  -- uint32
              dataWrite19 => dataWrite19_tmp,  -- uint32
              dataWrite20 => dataWrite20_tmp,  -- uint32
              dataWrite21 => dataWrite21_tmp,  -- uint32
              dataWrite22 => dataWrite22_tmp,  -- uint32
              dataWrite23 => dataWrite23_tmp,  -- uint32
              dataReadAXI0 => dataReadAXI0_tmp,  -- uint32
              dataReadAXI1 => dataReadAXI1_tmp,  -- uint32
              dataReadAXI2 => dataReadAXI2_tmp,  -- uint32
              dataReadAXI3 => dataReadAXI3_tmp,  -- uint32
              dataReadAXI4 => dataReadAXI4_tmp,  -- uint32
              dataReadAXI5 => dataReadAXI5_tmp,  -- uint32
              dataReadAXI6 => dataReadAXI6_tmp,  -- uint32
              dataReadAXI7 => dataReadAXI7_tmp,  -- uint32
              dataReadAXI8 => dataReadAXI8_tmp,  -- uint32
              dataReadAXI9 => dataReadAXI9_tmp,  -- uint32
              dataReadAXI10 => dataReadAXI10_tmp,  -- uint32
              dataReadAXI11 => dataReadAXI11_tmp,  -- uint32
              dataReadAXI12 => dataReadAXI12_tmp,  -- uint32
              dataReadAXI13 => dataReadAXI13_tmp,  -- uint32
              dataReadAXI14 => dataReadAXI14_tmp,  -- uint32
              dataReadAXI15 => dataReadAXI15_tmp,  -- uint32
              dataReadAXI16 => dataReadAXI16_tmp,  -- uint32
              dataReadAXI17 => dataReadAXI17_tmp,  -- uint32
              dataReadAXI18 => dataReadAXI18_tmp,  -- uint32
              dataReadAXI19 => dataReadAXI19_tmp,  -- uint32
              dataReadAXI20 => dataReadAXI20_tmp,  -- uint32
              dataReadAXI21 => dataReadAXI21_tmp,  -- uint32
              dataReadAXI22 => dataReadAXI22_tmp,  -- uint32
              dataReadAXI23 => dataReadAXI23_tmp  -- uint32
              );

  ce_out <= clk_enable;

  dataWrite0 <= dataWrite0_tmp;

  dataWrite1 <= dataWrite1_tmp;

  dataWrite2 <= dataWrite2_tmp;

  dataWrite3 <= dataWrite3_tmp;

  dataWrite4 <= dataWrite4_tmp;

  dataWrite5 <= dataWrite5_tmp;

  dataWrite6 <= dataWrite6_tmp;

  dataWrite7 <= dataWrite7_tmp;

  dataReadAXI0 <= dataReadAXI0_tmp;

  dataReadAXI1 <= dataReadAXI1_tmp;

  dataReadAXI2 <= dataReadAXI2_tmp;

  dataReadAXI3 <= dataReadAXI3_tmp;

  dataReadAXI4 <= dataReadAXI4_tmp;

  dataReadAXI5 <= dataReadAXI5_tmp;

  dataReadAXI6 <= dataReadAXI6_tmp;

  dataReadAXI7 <= dataReadAXI7_tmp;

  dataWrite8 <= dataWrite8_tmp;

  dataWrite9 <= dataWrite9_tmp;

  dataWrite10 <= dataWrite10_tmp;

  dataWrite11 <= dataWrite11_tmp;

  dataWrite12 <= dataWrite12_tmp;

  dataWrite13 <= dataWrite13_tmp;

  dataWrite14 <= dataWrite14_tmp;

  dataWrite15 <= dataWrite15_tmp;

  dataReadAXI8 <= dataReadAXI8_tmp;

  dataReadAXI9 <= dataReadAXI9_tmp;

  dataReadAXI10 <= dataReadAXI10_tmp;

  dataReadAXI11 <= dataReadAXI11_tmp;

  dataReadAXI12 <= dataReadAXI12_tmp;

  dataReadAXI13 <= dataReadAXI13_tmp;

  dataReadAXI14 <= dataReadAXI14_tmp;

  dataReadAXI15 <= dataReadAXI15_tmp;

  dataWrite16 <= dataWrite16_tmp;

  dataWrite17 <= dataWrite17_tmp;

  dataWrite18 <= dataWrite18_tmp;

  dataWrite19 <= dataWrite19_tmp;

  dataWrite20 <= dataWrite20_tmp;

  dataWrite21 <= dataWrite21_tmp;

  dataWrite22 <= dataWrite22_tmp;

  dataWrite23 <= dataWrite23_tmp;

  dataReadAXI16 <= dataReadAXI16_tmp;

  dataReadAXI17 <= dataReadAXI17_tmp;

  dataReadAXI18 <= dataReadAXI18_tmp;

  dataReadAXI19 <= dataReadAXI19_tmp;

  dataReadAXI20 <= dataReadAXI20_tmp;

  dataReadAXI21 <= dataReadAXI21_tmp;

  dataReadAXI22 <= dataReadAXI22_tmp;

  dataReadAXI23 <= dataReadAXI23_tmp;

END rtl;

