-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor_16regs\monitor_16regs_src_MATLAB_Function.vhd
-- Created: 2024-12-24 12:13:32
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: monitor_16regs_src_MATLAB_Function
-- Source Path: monitor_16regs/monitor_16regs_dut/MATLAB Function
-- Hierarchy Level: 1
-- Model version: 5.11
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY monitor_16regs_src_MATLAB_Function IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataWriteAXI0                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI1                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI2                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI3                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI4                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI5                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI6                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI7                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI8                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI9                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI10                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI11                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI12                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI13                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI14                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI15                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead9                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead10                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead11                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead12                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead13                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead14                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead15                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite4                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite5                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite6                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite7                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite8                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite9                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite10                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite11                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite12                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite13                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite14                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite15                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI8                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI9                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI10                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI11                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI12                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI13                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI14                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI15                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END monitor_16regs_src_MATLAB_Function;


ARCHITECTURE rtl OF monitor_16regs_src_MATLAB_Function IS

  -- Signals
  SIGNAL dataWriteAXI0_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI1_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI2_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI3_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI4_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI5_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI6_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI7_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI8_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI9_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI10_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI11_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI12_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI13_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI14_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWriteAXI15_unsigned          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead0_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead1_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead2_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead3_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead4_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead5_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead6_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead7_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead8_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead9_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead10_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead11_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead12_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead13_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead14_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataRead15_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite0_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite1_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite2_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite3_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite4_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite5_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite6_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite7_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite8_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite9_tmp                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite10_tmp                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite11_tmp                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite12_tmp                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite13_tmp                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite14_tmp                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataWrite15_tmp                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI0_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI1_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI2_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI3_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI4_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI5_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI6_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI7_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI8_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI9_tmp                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI10_tmp                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI11_tmp                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI12_tmp                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI13_tmp                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI14_tmp                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataReadAXI15_tmp                : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  dataWriteAXI0_unsigned <= unsigned(dataWriteAXI0);

  dataWriteAXI1_unsigned <= unsigned(dataWriteAXI1);

  dataWriteAXI2_unsigned <= unsigned(dataWriteAXI2);

  dataWriteAXI3_unsigned <= unsigned(dataWriteAXI3);

  dataWriteAXI4_unsigned <= unsigned(dataWriteAXI4);

  dataWriteAXI5_unsigned <= unsigned(dataWriteAXI5);

  dataWriteAXI6_unsigned <= unsigned(dataWriteAXI6);

  dataWriteAXI7_unsigned <= unsigned(dataWriteAXI7);

  dataWriteAXI8_unsigned <= unsigned(dataWriteAXI8);

  dataWriteAXI9_unsigned <= unsigned(dataWriteAXI9);

  dataWriteAXI10_unsigned <= unsigned(dataWriteAXI10);

  dataWriteAXI11_unsigned <= unsigned(dataWriteAXI11);

  dataWriteAXI12_unsigned <= unsigned(dataWriteAXI12);

  dataWriteAXI13_unsigned <= unsigned(dataWriteAXI13);

  dataWriteAXI14_unsigned <= unsigned(dataWriteAXI14);

  dataWriteAXI15_unsigned <= unsigned(dataWriteAXI15);

  dataRead0_unsigned <= unsigned(dataRead0);

  dataRead1_unsigned <= unsigned(dataRead1);

  dataRead2_unsigned <= unsigned(dataRead2);

  dataRead3_unsigned <= unsigned(dataRead3);

  dataRead4_unsigned <= unsigned(dataRead4);

  dataRead5_unsigned <= unsigned(dataRead5);

  dataRead6_unsigned <= unsigned(dataRead6);

  dataRead7_unsigned <= unsigned(dataRead7);

  dataRead8_unsigned <= unsigned(dataRead8);

  dataRead9_unsigned <= unsigned(dataRead9);

  dataRead10_unsigned <= unsigned(dataRead10);

  dataRead11_unsigned <= unsigned(dataRead11);

  dataRead12_unsigned <= unsigned(dataRead12);

  dataRead13_unsigned <= unsigned(dataRead13);

  dataRead14_unsigned <= unsigned(dataRead14);

  dataRead15_unsigned <= unsigned(dataRead15);

  MATLAB_Function_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataWrite0_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite1_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite2_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite3_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite4_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite5_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite6_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite7_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite8_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite9_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite10_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite11_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite12_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite13_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite14_tmp <= to_unsigned(16#00000000#, 32);
      dataWrite15_tmp <= to_unsigned(16#00000000#, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dataWrite0_tmp <= dataWriteAXI0_unsigned;
        dataWrite1_tmp <= dataWriteAXI1_unsigned;
        dataWrite2_tmp <= dataWriteAXI2_unsigned;
        dataWrite3_tmp <= dataWriteAXI3_unsigned;
        dataWrite4_tmp <= dataWriteAXI4_unsigned;
        dataWrite5_tmp <= dataWriteAXI5_unsigned;
        dataWrite6_tmp <= dataWriteAXI6_unsigned;
        dataWrite7_tmp <= dataWriteAXI7_unsigned;
        dataWrite8_tmp <= dataWriteAXI8_unsigned;
        dataWrite9_tmp <= dataWriteAXI9_unsigned;
        dataWrite10_tmp <= dataWriteAXI10_unsigned;
        dataWrite11_tmp <= dataWriteAXI11_unsigned;
        dataWrite12_tmp <= dataWriteAXI12_unsigned;
        dataWrite13_tmp <= dataWriteAXI13_unsigned;
        dataWrite14_tmp <= dataWriteAXI14_unsigned;
        dataWrite15_tmp <= dataWriteAXI15_unsigned;
      END IF;
    END IF;
  END PROCESS MATLAB_Function_process;

  dataReadAXI0_tmp <= dataRead0_unsigned;
  dataReadAXI1_tmp <= dataRead1_unsigned;
  dataReadAXI2_tmp <= dataRead2_unsigned;
  dataReadAXI3_tmp <= dataRead3_unsigned;
  dataReadAXI4_tmp <= dataRead4_unsigned;
  dataReadAXI5_tmp <= dataRead5_unsigned;
  dataReadAXI6_tmp <= dataRead6_unsigned;
  dataReadAXI7_tmp <= dataRead7_unsigned;
  dataReadAXI8_tmp <= dataRead8_unsigned;
  dataReadAXI9_tmp <= dataRead9_unsigned;
  dataReadAXI10_tmp <= dataRead10_unsigned;
  dataReadAXI11_tmp <= dataRead11_unsigned;
  dataReadAXI12_tmp <= dataRead12_unsigned;
  dataReadAXI13_tmp <= dataRead13_unsigned;
  dataReadAXI14_tmp <= dataRead14_unsigned;
  dataReadAXI15_tmp <= dataRead15_unsigned;

  dataWrite0 <= std_logic_vector(dataWrite0_tmp);

  dataWrite1 <= std_logic_vector(dataWrite1_tmp);

  dataWrite2 <= std_logic_vector(dataWrite2_tmp);

  dataWrite3 <= std_logic_vector(dataWrite3_tmp);

  dataWrite4 <= std_logic_vector(dataWrite4_tmp);

  dataWrite5 <= std_logic_vector(dataWrite5_tmp);

  dataWrite6 <= std_logic_vector(dataWrite6_tmp);

  dataWrite7 <= std_logic_vector(dataWrite7_tmp);

  dataWrite8 <= std_logic_vector(dataWrite8_tmp);

  dataWrite9 <= std_logic_vector(dataWrite9_tmp);

  dataWrite10 <= std_logic_vector(dataWrite10_tmp);

  dataWrite11 <= std_logic_vector(dataWrite11_tmp);

  dataWrite12 <= std_logic_vector(dataWrite12_tmp);

  dataWrite13 <= std_logic_vector(dataWrite13_tmp);

  dataWrite14 <= std_logic_vector(dataWrite14_tmp);

  dataWrite15 <= std_logic_vector(dataWrite15_tmp);

  dataReadAXI0 <= std_logic_vector(dataReadAXI0_tmp);

  dataReadAXI1 <= std_logic_vector(dataReadAXI1_tmp);

  dataReadAXI2 <= std_logic_vector(dataReadAXI2_tmp);

  dataReadAXI3 <= std_logic_vector(dataReadAXI3_tmp);

  dataReadAXI4 <= std_logic_vector(dataReadAXI4_tmp);

  dataReadAXI5 <= std_logic_vector(dataReadAXI5_tmp);

  dataReadAXI6 <= std_logic_vector(dataReadAXI6_tmp);

  dataReadAXI7 <= std_logic_vector(dataReadAXI7_tmp);

  dataReadAXI8 <= std_logic_vector(dataReadAXI8_tmp);

  dataReadAXI9 <= std_logic_vector(dataReadAXI9_tmp);

  dataReadAXI10 <= std_logic_vector(dataReadAXI10_tmp);

  dataReadAXI11 <= std_logic_vector(dataReadAXI11_tmp);

  dataReadAXI12 <= std_logic_vector(dataReadAXI12_tmp);

  dataReadAXI13 <= std_logic_vector(dataReadAXI13_tmp);

  dataReadAXI14 <= std_logic_vector(dataReadAXI14_tmp);

  dataReadAXI15 <= std_logic_vector(dataReadAXI15_tmp);

END rtl;

