-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_dut.vhd
-- Created: 2025-04-18 17:38:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_dut
-- Source Path: myCorrelator_ip/myCorrelator_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY myCorrelator_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        inphase_in                        :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        quadrature_in                     :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        valid_in                          :   IN    std_logic;  -- ufix1
        complexCoefRealIn_0               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_1               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_2               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_3               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_4               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_5               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_6               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_7               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_8               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_9               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_10              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_11              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_12              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_13              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_14              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_15              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_0               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_1               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_2               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_3               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_4               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_5               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_6               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_7               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_8               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_9               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_10              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_11              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_12              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_13              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_14              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_15              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        ce_out                            :   OUT   std_logic;  -- ufix1
        detectedRepeat                    :   OUT   std_logic  -- ufix1
        );
END myCorrelator_ip_dut;


ARCHITECTURE rtl OF myCorrelator_ip_dut IS

  -- Component Declarations
  COMPONENT myCorrelator_ip_src_myCorrelator
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          inphase_in                      :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          quadrature_in                   :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          valid_in                        :   IN    std_logic;  -- ufix1
          complexCoefRealIn_0             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_1             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_2             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_3             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_4             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_5             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_6             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_7             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_8             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_9             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_10            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_11            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_12            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_13            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_14            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_15            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_0             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_1             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_2             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_3             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_4             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_5             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_6             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_7             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_8             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_9             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_10            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_11            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_12            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_13            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_14            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_15            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          ce_out                          :   OUT   std_logic;  -- ufix1
          detectedRepeat                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : myCorrelator_ip_src_myCorrelator
    USE ENTITY work.myCorrelator_ip_src_myCorrelator(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL valid_in_sig                     : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL detectedRepeat_sig               : std_logic;  -- ufix1

BEGIN
  u_myCorrelator_ip_src_myCorrelator : myCorrelator_ip_src_myCorrelator
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              inphase_in => inphase_in,  -- sfix12
              quadrature_in => quadrature_in,  -- sfix12
              valid_in => valid_in_sig,  -- ufix1
              complexCoefRealIn_0 => complexCoefRealIn_0,  -- sfix6
              complexCoefRealIn_1 => complexCoefRealIn_1,  -- sfix6
              complexCoefRealIn_2 => complexCoefRealIn_2,  -- sfix6
              complexCoefRealIn_3 => complexCoefRealIn_3,  -- sfix6
              complexCoefRealIn_4 => complexCoefRealIn_4,  -- sfix6
              complexCoefRealIn_5 => complexCoefRealIn_5,  -- sfix6
              complexCoefRealIn_6 => complexCoefRealIn_6,  -- sfix6
              complexCoefRealIn_7 => complexCoefRealIn_7,  -- sfix6
              complexCoefRealIn_8 => complexCoefRealIn_8,  -- sfix6
              complexCoefRealIn_9 => complexCoefRealIn_9,  -- sfix6
              complexCoefRealIn_10 => complexCoefRealIn_10,  -- sfix6
              complexCoefRealIn_11 => complexCoefRealIn_11,  -- sfix6
              complexCoefRealIn_12 => complexCoefRealIn_12,  -- sfix6
              complexCoefRealIn_13 => complexCoefRealIn_13,  -- sfix6
              complexCoefRealIn_14 => complexCoefRealIn_14,  -- sfix6
              complexCoefRealIn_15 => complexCoefRealIn_15,  -- sfix6
              complexCoefImagIn_0 => complexCoefImagIn_0,  -- sfix6
              complexCoefImagIn_1 => complexCoefImagIn_1,  -- sfix6
              complexCoefImagIn_2 => complexCoefImagIn_2,  -- sfix6
              complexCoefImagIn_3 => complexCoefImagIn_3,  -- sfix6
              complexCoefImagIn_4 => complexCoefImagIn_4,  -- sfix6
              complexCoefImagIn_5 => complexCoefImagIn_5,  -- sfix6
              complexCoefImagIn_6 => complexCoefImagIn_6,  -- sfix6
              complexCoefImagIn_7 => complexCoefImagIn_7,  -- sfix6
              complexCoefImagIn_8 => complexCoefImagIn_8,  -- sfix6
              complexCoefImagIn_9 => complexCoefImagIn_9,  -- sfix6
              complexCoefImagIn_10 => complexCoefImagIn_10,  -- sfix6
              complexCoefImagIn_11 => complexCoefImagIn_11,  -- sfix6
              complexCoefImagIn_12 => complexCoefImagIn_12,  -- sfix6
              complexCoefImagIn_13 => complexCoefImagIn_13,  -- sfix6
              complexCoefImagIn_14 => complexCoefImagIn_14,  -- sfix6
              complexCoefImagIn_15 => complexCoefImagIn_15,  -- sfix6
              ce_out => ce_out_sig,  -- ufix1
              detectedRepeat => detectedRepeat_sig  -- ufix1
              );

  valid_in_sig <= valid_in;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  detectedRepeat <= detectedRepeat_sig;

END rtl;

