-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_src_Filter.vhd
-- Created: 2025-04-18 17:38:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_src_Filter
-- Source Path: myCorrelator/myCorrelator/Discrete FIR Filter/Filter
-- Hierarchy Level: 2
-- Model version: 8.511
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.myCorrelator_ip_src_myCorrelator_pkg.ALL;

ENTITY myCorrelator_ip_src_Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        dataIn_im                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        validIn                           :   IN    std_logic;
        coeff_re_0                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_1                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_2                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_3                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_4                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_5                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_6                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_7                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_8                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_9                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_10                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_11                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_12                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_13                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_14                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_re_15                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_0                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_1                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_2                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_3                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_4                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_5                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_6                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_7                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_8                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_9                        :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_10                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_11                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_12                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_13                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_14                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        coeff_im_15                       :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        syncReset                         :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22
        dataOut_im                        :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22
        );
END myCorrelator_ip_src_Filter;


ARCHITECTURE rtl OF myCorrelator_ip_src_Filter IS

  -- Component Declarations
  COMPONENT myCorrelator_ip_src_subFilter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13
          coefIn_0                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_1                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_2                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_3                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_4                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_5                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_6                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_7                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_8                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_9                        :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_10                       :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_11                       :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_12                       :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_13                       :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_14                       :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          coefIn_15                       :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dout_1_re                       :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : myCorrelator_ip_src_subFilter
    USE ENTITY work.myCorrelator_ip_src_subFilter(rtl);

  -- Signals
  SIGNAL dinRegVld                        : std_logic;
  SIGNAL dataIn_re_signed                 : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL dataIn_im_signed                 : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL dinReg_0_re                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL dinReg_cast_0_re                 : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL coeff_re                         : vector_of_signed6(0 TO 15);  -- sfix6 [16]
  SIGNAL coeff_im                         : vector_of_signed6(0 TO 15);  -- sfix6 [16]
  SIGNAL coeffIn_signed_re                : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL coeffIn_signed_im                : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL CoefReg1_re                      : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL CoefReg1_im                      : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL CoefP                            : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL CoefReg1_P                       : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL dinReg2_0_re                     : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL dinReg2Vld                       : std_logic;
  SIGNAL dout_1_P                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dout_1_P_signed                  : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL dinReg_0_im                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL dinRealPImag_0                   : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL CoefReg1_I                       : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL dinReg2_0_P                      : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL dout_1_I                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dout_1_I_signed                  : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL dout_1_r                         : signed(48 DOWNTO 0);  -- sfix49
  SIGNAL dout_1_cast_r                    : signed(21 DOWNTO 0);  -- sfix22
  SIGNAL dout_1_re                        : signed(21 DOWNTO 0);  -- sfix22
  SIGNAL dinReg2_cast_0_im                : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL CoefS                            : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL CoefReg1_M                       : vector_of_signed7(0 TO 15);  -- sfix7 [16]
  SIGNAL dinReg2_0_im                     : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL dout_1_M                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dout_1_M_signed                  : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL dout_1_i_1                       : signed(48 DOWNTO 0);  -- sfix49
  SIGNAL dout_1_cast_i                    : signed(21 DOWNTO 0);  -- sfix22
  SIGNAL dout_1_im                        : signed(21 DOWNTO 0);  -- sfix22

BEGIN
  u_subFilter_1_reP : myCorrelator_ip_src_subFilter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => std_logic_vector(dinReg2_0_re),  -- sfix13
              coefIn_0 => std_logic_vector(CoefReg1_P(0)),  -- sfix7
              coefIn_1 => std_logic_vector(CoefReg1_P(1)),  -- sfix7
              coefIn_2 => std_logic_vector(CoefReg1_P(2)),  -- sfix7
              coefIn_3 => std_logic_vector(CoefReg1_P(3)),  -- sfix7
              coefIn_4 => std_logic_vector(CoefReg1_P(4)),  -- sfix7
              coefIn_5 => std_logic_vector(CoefReg1_P(5)),  -- sfix7
              coefIn_6 => std_logic_vector(CoefReg1_P(6)),  -- sfix7
              coefIn_7 => std_logic_vector(CoefReg1_P(7)),  -- sfix7
              coefIn_8 => std_logic_vector(CoefReg1_P(8)),  -- sfix7
              coefIn_9 => std_logic_vector(CoefReg1_P(9)),  -- sfix7
              coefIn_10 => std_logic_vector(CoefReg1_P(10)),  -- sfix7
              coefIn_11 => std_logic_vector(CoefReg1_P(11)),  -- sfix7
              coefIn_12 => std_logic_vector(CoefReg1_P(12)),  -- sfix7
              coefIn_13 => std_logic_vector(CoefReg1_P(13)),  -- sfix7
              coefIn_14 => std_logic_vector(CoefReg1_P(14)),  -- sfix7
              coefIn_15 => std_logic_vector(CoefReg1_P(15)),  -- sfix7
              dinRegVld => dinReg2Vld,
              syncReset => syncReset,
              dout_1_re => dout_1_P  -- sfix48
              );

  u_subFilter_1_im : myCorrelator_ip_src_subFilter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => std_logic_vector(dinReg2_0_P),  -- sfix13
              coefIn_0 => std_logic_vector(CoefReg1_I(0)),  -- sfix7
              coefIn_1 => std_logic_vector(CoefReg1_I(1)),  -- sfix7
              coefIn_2 => std_logic_vector(CoefReg1_I(2)),  -- sfix7
              coefIn_3 => std_logic_vector(CoefReg1_I(3)),  -- sfix7
              coefIn_4 => std_logic_vector(CoefReg1_I(4)),  -- sfix7
              coefIn_5 => std_logic_vector(CoefReg1_I(5)),  -- sfix7
              coefIn_6 => std_logic_vector(CoefReg1_I(6)),  -- sfix7
              coefIn_7 => std_logic_vector(CoefReg1_I(7)),  -- sfix7
              coefIn_8 => std_logic_vector(CoefReg1_I(8)),  -- sfix7
              coefIn_9 => std_logic_vector(CoefReg1_I(9)),  -- sfix7
              coefIn_10 => std_logic_vector(CoefReg1_I(10)),  -- sfix7
              coefIn_11 => std_logic_vector(CoefReg1_I(11)),  -- sfix7
              coefIn_12 => std_logic_vector(CoefReg1_I(12)),  -- sfix7
              coefIn_13 => std_logic_vector(CoefReg1_I(13)),  -- sfix7
              coefIn_14 => std_logic_vector(CoefReg1_I(14)),  -- sfix7
              coefIn_15 => std_logic_vector(CoefReg1_I(15)),  -- sfix7
              dinRegVld => dinReg2Vld,
              syncReset => syncReset,
              dout_1_re => dout_1_I  -- sfix48
              );

  u_subFilter_1_reS : myCorrelator_ip_src_subFilter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => std_logic_vector(dinReg2_0_im),  -- sfix13
              coefIn_0 => std_logic_vector(CoefReg1_M(0)),  -- sfix7
              coefIn_1 => std_logic_vector(CoefReg1_M(1)),  -- sfix7
              coefIn_2 => std_logic_vector(CoefReg1_M(2)),  -- sfix7
              coefIn_3 => std_logic_vector(CoefReg1_M(3)),  -- sfix7
              coefIn_4 => std_logic_vector(CoefReg1_M(4)),  -- sfix7
              coefIn_5 => std_logic_vector(CoefReg1_M(5)),  -- sfix7
              coefIn_6 => std_logic_vector(CoefReg1_M(6)),  -- sfix7
              coefIn_7 => std_logic_vector(CoefReg1_M(7)),  -- sfix7
              coefIn_8 => std_logic_vector(CoefReg1_M(8)),  -- sfix7
              coefIn_9 => std_logic_vector(CoefReg1_M(9)),  -- sfix7
              coefIn_10 => std_logic_vector(CoefReg1_M(10)),  -- sfix7
              coefIn_11 => std_logic_vector(CoefReg1_M(11)),  -- sfix7
              coefIn_12 => std_logic_vector(CoefReg1_M(12)),  -- sfix7
              coefIn_13 => std_logic_vector(CoefReg1_M(13)),  -- sfix7
              coefIn_14 => std_logic_vector(CoefReg1_M(14)),  -- sfix7
              coefIn_15 => std_logic_vector(CoefReg1_M(15)),  -- sfix7
              dinRegVld => dinReg2Vld,
              syncReset => syncReset,
              dout_1_re => dout_1_M  -- sfix48
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinRegVld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinRegVld <= '0';
        ELSE 
          dinRegVld <= validIn;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  dataIn_re_signed <= signed(dataIn_re);

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg_0_re <= to_signed(16#000#, 12);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg_0_re <= to_signed(16#000#, 12);
        ELSIF validIn = '1' THEN
          dinReg_0_re <= dataIn_re_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dinReg_cast_0_re <= resize(dinReg_0_re, 13);

  coeff_re(0) <= signed(coeff_re_0);
  coeff_re(1) <= signed(coeff_re_1);
  coeff_re(2) <= signed(coeff_re_2);
  coeff_re(3) <= signed(coeff_re_3);
  coeff_re(4) <= signed(coeff_re_4);
  coeff_re(5) <= signed(coeff_re_5);
  coeff_re(6) <= signed(coeff_re_6);
  coeff_re(7) <= signed(coeff_re_7);
  coeff_re(8) <= signed(coeff_re_8);
  coeff_re(9) <= signed(coeff_re_9);
  coeff_re(10) <= signed(coeff_re_10);
  coeff_re(11) <= signed(coeff_re_11);
  coeff_re(12) <= signed(coeff_re_12);
  coeff_re(13) <= signed(coeff_re_13);
  coeff_re(14) <= signed(coeff_re_14);
  coeff_re(15) <= signed(coeff_re_15);

  coeff_im(0) <= signed(coeff_im_0);
  coeff_im(1) <= signed(coeff_im_1);
  coeff_im(2) <= signed(coeff_im_2);
  coeff_im(3) <= signed(coeff_im_3);
  coeff_im(4) <= signed(coeff_im_4);
  coeff_im(5) <= signed(coeff_im_5);
  coeff_im(6) <= signed(coeff_im_6);
  coeff_im(7) <= signed(coeff_im_7);
  coeff_im(8) <= signed(coeff_im_8);
  coeff_im(9) <= signed(coeff_im_9);
  coeff_im(10) <= signed(coeff_im_10);
  coeff_im(11) <= signed(coeff_im_11);
  coeff_im(12) <= signed(coeff_im_12);
  coeff_im(13) <= signed(coeff_im_13);
  coeff_im(14) <= signed(coeff_im_14);
  coeff_im(15) <= signed(coeff_im_15);


  coeffIn_signed_im_gen: FOR ii IN 0 TO 15 GENERATE
    coeffIn_signed_re(ii) <= resize(coeff_re(ii), 7);
    coeffIn_signed_im(ii) <= resize(coeff_im(ii), 7);
  END GENERATE coeffIn_signed_im_gen;


  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        CoefReg1_re <= (OTHERS => to_signed(16#00#, 7));
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          CoefReg1_re <= (OTHERS => to_signed(16#00#, 7));
        ELSIF validIn = '1' THEN
          CoefReg1_re <= coeffIn_signed_re;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  intdelay_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        CoefReg1_im <= (OTHERS => to_signed(16#00#, 7));
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          CoefReg1_im <= (OTHERS => to_signed(16#00#, 7));
        ELSIF validIn = '1' THEN
          CoefReg1_im <= coeffIn_signed_im;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;



  CoefP_gen: FOR t_0 IN 0 TO 15 GENERATE
    CoefP(t_0) <= CoefReg1_re(t_0) + CoefReg1_im(t_0);
  END GENERATE CoefP_gen;


  intdelay_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        CoefReg1_P <= (OTHERS => to_signed(16#00#, 7));
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          CoefReg1_P <= (OTHERS => to_signed(16#00#, 7));
        ELSIF dinRegVld = '1' THEN
          CoefReg1_P <= CoefP;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_4_process;


  intdelay_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg2_0_re <= to_signed(16#0000#, 13);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2_0_re <= to_signed(16#0000#, 13);
        ELSIF dinRegVld = '1' THEN
          dinReg2_0_re <= dinReg_cast_0_re;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_5_process;


  intdelay_6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg2Vld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2Vld <= '0';
        ELSE 
          dinReg2Vld <= dinRegVld;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_6_process;


  dout_1_P_signed <= signed(dout_1_P);

  dataIn_im_signed <= signed(dataIn_im);

  intdelay_7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg_0_im <= to_signed(16#000#, 12);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg_0_im <= to_signed(16#000#, 12);
        ELSIF validIn = '1' THEN
          dinReg_0_im <= dataIn_im_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_7_process;


  dinRealPImag_0 <= resize(dinReg_0_re, 13) + resize(dinReg_0_im, 13);

  intdelay_8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        CoefReg1_I <= (OTHERS => to_signed(16#00#, 7));
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          CoefReg1_I <= (OTHERS => to_signed(16#00#, 7));
        ELSIF dinRegVld = '1' THEN
          CoefReg1_I <= CoefReg1_im;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_8_process;


  intdelay_9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg2_0_P <= to_signed(16#0000#, 13);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2_0_P <= to_signed(16#0000#, 13);
        ELSIF dinRegVld = '1' THEN
          dinReg2_0_P <= dinRealPImag_0;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_9_process;


  dout_1_I_signed <= signed(dout_1_I);

  dout_1_r <= resize(dout_1_P_signed, 49) - resize(dout_1_I_signed, 49);

  dout_1_cast_r <= dout_1_r(21 DOWNTO 0);

  intdelay_10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re <= to_signed(16#000000#, 22);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re <= to_signed(16#000000#, 22);
        ELSE 
          dout_1_re <= dout_1_cast_r;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_10_process;


  dataOut_re <= std_logic_vector(dout_1_re);

  dinReg2_cast_0_im <= resize(dinReg_0_im, 13);


  CoefS_gen: FOR t_01 IN 0 TO 15 GENERATE
    CoefS(t_01) <= CoefReg1_re(t_01) - CoefReg1_im(t_01);
  END GENERATE CoefS_gen;


  intdelay_11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        CoefReg1_M <= (OTHERS => to_signed(16#00#, 7));
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          CoefReg1_M <= (OTHERS => to_signed(16#00#, 7));
        ELSIF dinRegVld = '1' THEN
          CoefReg1_M <= CoefS;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_11_process;


  intdelay_12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg2_0_im <= to_signed(16#0000#, 13);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2_0_im <= to_signed(16#0000#, 13);
        ELSIF dinRegVld = '1' THEN
          dinReg2_0_im <= dinReg2_cast_0_im;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_12_process;


  dout_1_M_signed <= signed(dout_1_M);

  dout_1_i_1 <= resize(dout_1_M_signed, 49) + resize(dout_1_I_signed, 49);

  dout_1_cast_i <= dout_1_i_1(21 DOWNTO 0);

  intdelay_13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_im <= to_signed(16#000000#, 22);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_im <= to_signed(16#000000#, 22);
        ELSE 
          dout_1_im <= dout_1_cast_i;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_13_process;


  dataOut_im <= std_logic_vector(dout_1_im);

END rtl;

