-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_src_myCorrelator.vhd
-- Created: 2025-04-18 17:38:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- detectedRepeat                ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_src_myCorrelator
-- Source Path: myCorrelator/myCorrelator
-- Hierarchy Level: 0
-- Model version: 8.511
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.myCorrelator_ip_src_myCorrelator_pkg.ALL;

ENTITY myCorrelator_ip_src_myCorrelator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        inphase_in                        :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        quadrature_in                     :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        valid_in                          :   IN    std_logic;
        complexCoefRealIn_0               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_1               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_2               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_3               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_4               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_5               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_6               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_7               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_8               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_9               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_10              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_11              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_12              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_13              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_14              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefRealIn_15              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_0               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_1               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_2               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_3               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_4               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_5               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_6               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_7               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_8               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_9               :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_10              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_11              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_12              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_13              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_14              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        complexCoefImagIn_15              :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
        ce_out                            :   OUT   std_logic;
        detectedRepeat                    :   OUT   std_logic  -- ufix1
        );
END myCorrelator_ip_src_myCorrelator;


ARCHITECTURE rtl OF myCorrelator_ip_src_myCorrelator IS

  -- Component Declarations
  COMPONENT myCorrelator_ip_src_Discrete_FIR_Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          dataIn_im                       :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          validIn                         :   IN    std_logic;
          coeff_re_0                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_1                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_2                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_3                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_4                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_5                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_6                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_7                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_8                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_9                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_10                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_11                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_12                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_13                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_14                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_re_15                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_0                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_1                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_2                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_3                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_4                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_5                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_6                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_7                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_8                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_9                      :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_10                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_11                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_12                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_13                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_14                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          coeff_im_15                     :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          dataOut_re                      :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22
          dataOut_im                      :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22
          );
  END COMPONENT;

  COMPONENT myCorrelator_ip_src_Calculate_xcorr_sum_s_a_2_s_b_2_latency_0
    PORT( real_in                         :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22
          imag_in                         :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22
          normSquare                      :   OUT   std_logic_vector(44 DOWNTO 0)  -- sfix45
          );
  END COMPONENT;

  COMPONENT myCorrelator_ip_src_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          real_in                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          imag_in                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          validIn                         :   IN    std_logic;
          energy                          :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29
          );
  END COMPONENT;

  COMPONENT myCorrelator_ip_src_Comparator_latency_0
    PORT( xcorrSquareIn                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          acorrSquareIn                   :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29
          detected                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT myCorrelator_ip_src_Detector_latency_1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          detected                        :   IN    std_logic;  -- ufix1
          validIn                         :   IN    std_logic;
          detectedRepeat                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : myCorrelator_ip_src_Discrete_FIR_Filter
    USE ENTITY work.myCorrelator_ip_src_Discrete_FIR_Filter(rtl);

  FOR ALL : myCorrelator_ip_src_Calculate_xcorr_sum_s_a_2_s_b_2_latency_0
    USE ENTITY work.myCorrelator_ip_src_Calculate_xcorr_sum_s_a_2_s_b_2_latency_0(rtl);

  FOR ALL : myCorrelator_ip_src_Subsystem
    USE ENTITY work.myCorrelator_ip_src_Subsystem(rtl);

  FOR ALL : myCorrelator_ip_src_Comparator_latency_0
    USE ENTITY work.myCorrelator_ip_src_Comparator_latency_0(rtl);

  FOR ALL : myCorrelator_ip_src_Detector_latency_1
    USE ENTITY work.myCorrelator_ip_src_Detector_latency_1(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL validIn                          : std_logic;
  SIGNAL complexCorrOut_re                : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL complexCorrOut_im                : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL resultI                          : signed(21 DOWNTO 0);  -- sfix22
  SIGNAL resultI_1                        : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL resultQ                          : signed(21 DOWNTO 0);  -- sfix22
  SIGNAL resultQ_1                        : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL xcorrSquare                      : std_logic_vector(44 DOWNTO 0);  -- ufix45
  SIGNAL xcorrSquare_signed               : signed(44 DOWNTO 0);  -- sfix45
  SIGNAL xcorrSquareAfterShift            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL inphase_in_signed                : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL quadrature_in_signed             : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Delay1_bypass_delay              : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Delay1_reg                       : vector_of_signed12(0 TO 5);  -- sfix12 [6]
  SIGNAL Delay1_out1                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Delay3_bypass_delay              : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Delay3_reg                       : vector_of_signed12(0 TO 5);  -- sfix12 [6]
  SIGNAL Delay3_out1                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL energy                           : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL energy_signed                    : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL Delay4_bypass_delay              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay4_reg                       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL xcorrSquareAfterDiv              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay2_bypass_delay              : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL Delay2_reg                       : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL acorrSquare                      : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL detected                         : std_logic;  -- ufix1

BEGIN
  u_Discrete_FIR_Filter : myCorrelator_ip_src_Discrete_FIR_Filter
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn_re => inphase_in,  -- sfix12
              dataIn_im => quadrature_in,  -- sfix12
              validIn => validIn,
              coeff_re_0 => complexCoefRealIn_0,  -- sfix6
              coeff_re_1 => complexCoefRealIn_1,  -- sfix6
              coeff_re_2 => complexCoefRealIn_2,  -- sfix6
              coeff_re_3 => complexCoefRealIn_3,  -- sfix6
              coeff_re_4 => complexCoefRealIn_4,  -- sfix6
              coeff_re_5 => complexCoefRealIn_5,  -- sfix6
              coeff_re_6 => complexCoefRealIn_6,  -- sfix6
              coeff_re_7 => complexCoefRealIn_7,  -- sfix6
              coeff_re_8 => complexCoefRealIn_8,  -- sfix6
              coeff_re_9 => complexCoefRealIn_9,  -- sfix6
              coeff_re_10 => complexCoefRealIn_10,  -- sfix6
              coeff_re_11 => complexCoefRealIn_11,  -- sfix6
              coeff_re_12 => complexCoefRealIn_12,  -- sfix6
              coeff_re_13 => complexCoefRealIn_13,  -- sfix6
              coeff_re_14 => complexCoefRealIn_14,  -- sfix6
              coeff_re_15 => complexCoefRealIn_15,  -- sfix6
              coeff_im_0 => complexCoefImagIn_0,  -- sfix6
              coeff_im_1 => complexCoefImagIn_1,  -- sfix6
              coeff_im_2 => complexCoefImagIn_2,  -- sfix6
              coeff_im_3 => complexCoefImagIn_3,  -- sfix6
              coeff_im_4 => complexCoefImagIn_4,  -- sfix6
              coeff_im_5 => complexCoefImagIn_5,  -- sfix6
              coeff_im_6 => complexCoefImagIn_6,  -- sfix6
              coeff_im_7 => complexCoefImagIn_7,  -- sfix6
              coeff_im_8 => complexCoefImagIn_8,  -- sfix6
              coeff_im_9 => complexCoefImagIn_9,  -- sfix6
              coeff_im_10 => complexCoefImagIn_10,  -- sfix6
              coeff_im_11 => complexCoefImagIn_11,  -- sfix6
              coeff_im_12 => complexCoefImagIn_12,  -- sfix6
              coeff_im_13 => complexCoefImagIn_13,  -- sfix6
              coeff_im_14 => complexCoefImagIn_14,  -- sfix6
              coeff_im_15 => complexCoefImagIn_15,  -- sfix6
              dataOut_re => complexCorrOut_re,  -- sfix22
              dataOut_im => complexCorrOut_im  -- sfix22
              );

  u_Calculate_xcorr_sum_s_a_2_s_b_2_latency_0 : myCorrelator_ip_src_Calculate_xcorr_sum_s_a_2_s_b_2_latency_0
    PORT MAP( real_in => resultI_1,  -- sfix22
              imag_in => resultQ_1,  -- sfix22
              normSquare => xcorrSquare  -- sfix45
              );

  u_Subsystem : myCorrelator_ip_src_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              real_in => std_logic_vector(Delay1_out1),  -- sfix12
              imag_in => std_logic_vector(Delay3_out1),  -- sfix12
              validIn => validIn,
              energy => energy  -- sfix29
              );

  u_Comparator_latency_0 : myCorrelator_ip_src_Comparator_latency_0
    PORT MAP( xcorrSquareIn => std_logic_vector(xcorrSquareAfterDiv),  -- uint32
              acorrSquareIn => std_logic_vector(acorrSquare),  -- sfix29
              detected => detected  -- ufix1
              );

  u_Detector_latency_1 : myCorrelator_ip_src_Detector_latency_1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              detected => detected,  -- ufix1
              validIn => validIn,
              detectedRepeat => detectedRepeat  -- ufix1
              );

  validIn <= valid_in;

  resultI <= signed(complexCorrOut_re);

  resultI_1 <= std_logic_vector(resultI);

  resultQ <= signed(complexCorrOut_im);

  resultQ_1 <= std_logic_vector(resultQ);

  xcorrSquare_signed <= signed(xcorrSquare);

  xcorrSquareAfterShift <= unsigned(xcorrSquare_signed(44 DOWNTO 13));

  enb <= clk_enable;

  inphase_in_signed <= signed(inphase_in);

  quadrature_in_signed <= signed(quadrature_in);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_bypass_delay <= to_signed(16#000#, 12);
        Delay1_reg <= (OTHERS => to_signed(16#000#, 12));
      ELSIF enb = '1' AND validIn = '1' THEN
        Delay1_bypass_delay <= Delay1_reg(5);
        Delay1_reg(0) <= inphase_in_signed;
        Delay1_reg(1 TO 5) <= Delay1_reg(0 TO 4);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  
  Delay1_out1 <= Delay1_reg(5) WHEN validIn = '1' ELSE
      Delay1_bypass_delay;

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_bypass_delay <= to_signed(16#000#, 12);
        Delay3_reg <= (OTHERS => to_signed(16#000#, 12));
      ELSIF enb = '1' AND validIn = '1' THEN
        Delay3_bypass_delay <= Delay3_reg(5);
        Delay3_reg(0) <= quadrature_in_signed;
        Delay3_reg(1 TO 5) <= Delay3_reg(0 TO 4);
      END IF;
    END IF;
  END PROCESS Delay3_process;

  
  Delay3_out1 <= Delay3_reg(5) WHEN validIn = '1' ELSE
      Delay3_bypass_delay;

  energy_signed <= signed(energy);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_bypass_delay <= to_unsigned(0, 32);
        Delay4_reg <= to_unsigned(0, 32);
      ELSIF enb = '1' AND validIn = '1' THEN
        Delay4_bypass_delay <= Delay4_reg;
        Delay4_reg <= xcorrSquareAfterShift;
      END IF;
    END IF;
  END PROCESS Delay4_process;

  
  xcorrSquareAfterDiv <= Delay4_reg WHEN validIn = '1' ELSE
      Delay4_bypass_delay;

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_bypass_delay <= to_signed(16#00000000#, 29);
        Delay2_reg <= to_signed(16#00000000#, 29);
      ELSIF enb = '1' AND validIn = '1' THEN
        Delay2_bypass_delay <= Delay2_reg;
        Delay2_reg <= energy_signed;
      END IF;
    END IF;
  END PROCESS Delay2_process;

  
  acorrSquare <= Delay2_reg WHEN validIn = '1' ELSE
      Delay2_bypass_delay;

  ce_out <= clk_enable;

END rtl;

