-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_src_FilterTapWvldIn.vhd
-- Created: 2025-04-18 17:38:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_src_FilterTapWvldIn
-- Source Path: myCorrelator/myCorrelator/Discrete FIR Filter/Filter/subFilter/FilterTapWvldIn
-- Hierarchy Level: 4
-- Model version: 8.511
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY myCorrelator_ip_src_FilterTapWvldIn IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13
        coefIn_15                         :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        addin                             :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48
        multVld                           :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        tapout                            :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48
        );
END myCorrelator_ip_src_FilterTapWvldIn;


ARCHITECTURE rtl OF myCorrelator_ip_src_FilterTapWvldIn IS

  -- Signals
  SIGNAL dinReg2_0_re_signed              : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL coefIn_15_signed                 : signed(6 DOWNTO 0);  -- sfix7
  SIGNAL addin_signed                     : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL fTap_din_reg                     : signed(12 DOWNTO 0) := to_signed(16#0000#, 13);  -- sfix13
  SIGNAL fTap_coef_reg                    : signed(6 DOWNTO 0) := to_signed(16#00#, 7);  -- sfix7
  SIGNAL fTap_mult_reg                    : signed(19 DOWNTO 0) := to_signed(16#00000#, 20);  -- sfix20
  SIGNAL fTap_addout_reg                  : signed(47 DOWNTO 0) := to_signed(0, 48);  -- sfix48
  SIGNAL fTap_din_reg_next                : signed(12 DOWNTO 0);  -- sfix13
  SIGNAL fTap_coef_reg_next               : signed(6 DOWNTO 0);  -- sfix7
  SIGNAL fTap_mult_reg_next               : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL fTap_addout_reg_next             : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL tapout_tmp                       : signed(47 DOWNTO 0);  -- sfix48

BEGIN
  dinReg2_0_re_signed <= signed(dinReg2_0_re);

  coefIn_15_signed <= signed(coefIn_15);

  addin_signed <= signed(addin);

  -- FilterTap
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          fTap_din_reg <= to_signed(16#0000#, 13);
          fTap_coef_reg <= to_signed(16#00#, 7);
          fTap_mult_reg <= to_signed(16#00000#, 20);
          fTap_addout_reg <= to_signed(0, 48);
        ELSE 
          fTap_din_reg <= fTap_din_reg_next;
          fTap_coef_reg <= fTap_coef_reg_next;
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
        END IF;
      END IF;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, coefIn_15_signed, dinReg2_0_re_signed, fTap_addout_reg,
       fTap_coef_reg, fTap_din_reg, fTap_mult_reg, multVld)
  BEGIN
    fTap_addout_reg_next <= fTap_addout_reg;
    tapout_tmp <= fTap_addout_reg;
    IF multVld = '1' THEN 
      fTap_addout_reg_next <= resize(fTap_mult_reg, 48) + addin_signed;
    END IF;
    fTap_mult_reg_next <= fTap_din_reg * fTap_coef_reg;
    fTap_din_reg_next <= dinReg2_0_re_signed;
    fTap_coef_reg_next <= coefIn_15_signed;
  END PROCESS fTap_output;


  tapout <= std_logic_vector(tapout_tmp);

END rtl;

