-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_src_Comparator_latency_0.vhd
-- Created: 2025-04-18 17:38:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_src_Comparator_latency_0
-- Source Path: myCorrelator/myCorrelator/Comparator, latency:0
-- Hierarchy Level: 1
-- Model version: 8.511
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY myCorrelator_ip_src_Comparator_latency_0 IS
  PORT( xcorrSquareIn                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        acorrSquareIn                     :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29
        detected                          :   OUT   std_logic  -- ufix1
        );
END myCorrelator_ip_src_Comparator_latency_0;


ARCHITECTURE rtl OF myCorrelator_ip_src_Comparator_latency_0 IS

  -- Signals
  SIGNAL xcorrSquareIn_unsigned           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL acorrSquareIn_signed             : signed(28 DOWNTO 0);  -- sfix29

BEGIN
  xcorrSquareIn_unsigned <= unsigned(xcorrSquareIn);

  acorrSquareIn_signed <= signed(acorrSquareIn);

  Comparator_latency_0_output : PROCESS (acorrSquareIn_signed, xcorrSquareIn_unsigned)
    VARIABLE cast : unsigned(31 DOWNTO 0);
  BEGIN
    -- Update registers
    cast := unsigned(resize(acorrSquareIn_signed, 32));
    IF xcorrSquareIn_unsigned > cast THEN 
      detected <= '1';
    ELSE 
      detected <= '0';
    END IF;
  END PROCESS Comparator_latency_0_output;


END rtl;

