-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_src_Detector_latency_1.vhd
-- Created: 2025-04-18 17:38:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_src_Detector_latency_1
-- Source Path: myCorrelator/myCorrelator/Detector, latency: 1
-- Hierarchy Level: 1
-- Model version: 8.511
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.myCorrelator_ip_src_myCorrelator_pkg.ALL;

ENTITY myCorrelator_ip_src_Detector_latency_1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        detected                          :   IN    std_logic;  -- ufix1
        validIn                           :   IN    std_logic;
        detectedRepeat                    :   OUT   std_logic  -- ufix1
        );
END myCorrelator_ip_src_Detector_latency_1;


ARCHITECTURE rtl OF myCorrelator_ip_src_Detector_latency_1 IS

  -- Constants
  CONSTANT nc                             : vector_of_signed32(0 TO 3) := 
    (to_signed(16#00000000#, 32), to_signed(16#00000010#, 32), to_signed(16#00000020#, 32),
     to_signed(16#00000030#, 32));  -- int32 [4]

  -- Signals
  SIGNAL detectorCntSingle                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL detectionHistory                 : std_logic_vector(48 DOWNTO 0);  -- ufix1 [49]
  SIGNAL detectorCntSingle_reg            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL detectionHistory_next            : std_logic_vector(48 DOWNTO 0);  -- ufix1 [49]
  SIGNAL detectorCntSingle_reg_next       : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  Detector_latency_1_process : PROCESS (clk)
    VARIABLE t_1 : INTEGER;
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN

        FOR t_1 IN 0 TO 48 LOOP
          detectionHistory(t_1) <= '0';
        END LOOP;

        detectorCntSingle_reg <= to_unsigned(16#00000000#, 32);
      ELSIF enb = '1' THEN

        FOR t_0 IN 0 TO 48 LOOP
          detectionHistory(t_0) <= detectionHistory_next(t_0);
        END LOOP;

        detectorCntSingle_reg <= detectorCntSingle_reg_next;
      END IF;
    END IF;
  END PROCESS Detector_latency_1_process;

  Detector_latency_1_output : PROCESS (detected, detectionHistory, detectorCntSingle_reg, validIn)
    VARIABLE y : std_logic;
    VARIABLE t_0 : std_logic_vector(48 DOWNTO 0);
  BEGIN

    FOR t_3 IN 0 TO 48 LOOP
      detectionHistory_next(t_3) <= detectionHistory(t_3);
    END LOOP;

    detectorCntSingle_reg_next <= detectorCntSingle_reg;
    -- Set outputs
    y := '1';

    FOR k IN 0 TO 3 LOOP
      y := y AND detectionHistory(to_integer(nc(k)));
    END LOOP;

    IF y = '1' THEN 
      detectedRepeat <= '1';
    ELSE 
      detectedRepeat <= '0';
    END IF;
    -- Update registers
    IF validIn = '1' THEN 
      IF detected = '1' THEN 
        detectorCntSingle_reg_next <= detectorCntSingle_reg + 1;
      END IF;
      t_0(0) := detected;

      FOR t_1 IN 0 TO 47 LOOP
        t_0(t_1 + 1) := detectionHistory(t_1);
      END LOOP;


      FOR t_2 IN 0 TO 48 LOOP
        detectionHistory_next(t_2) <= t_0(t_2);
      END LOOP;

    END IF;
    detectorCntSingle <= detectorCntSingle_reg;
  END PROCESS Detector_latency_1_output;


END rtl;

