-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_src_subFilter.vhd
-- Created: 2025-04-18 17:38:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_src_subFilter
-- Source Path: myCorrelator/myCorrelator/Discrete FIR Filter/Filter/subFilter
-- Hierarchy Level: 3
-- Model version: 8.511
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY myCorrelator_ip_src_subFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13
        coefIn_0                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_1                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_2                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_3                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_4                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_5                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_6                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_7                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_8                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_9                          :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_10                         :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_11                         :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_12                         :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_13                         :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_14                         :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        coefIn_15                         :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48
        );
END myCorrelator_ip_src_subFilter;


ARCHITECTURE rtl OF myCorrelator_ip_src_subFilter IS

  -- Component Declarations
  COMPONENT myCorrelator_ip_src_FilterTapWvldIn
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13
          coefIn_15                       :   IN    std_logic_vector(6 DOWNTO 0);  -- sfix7
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48
          multVld                         :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : myCorrelator_ip_src_FilterTapWvldIn
    USE ENTITY work.myCorrelator_ip_src_FilterTapWvldIn(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL tapoutVld                        : std_logic;
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL intdelay_reg_1                   : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL multVld                          : std_logic;
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_3                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_4                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_5                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_6                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_7                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_8                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_9                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_10                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_11                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_12                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_13                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_14                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL ZERO_OUT                         : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL tapout_15                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL muxOut                           : signed(47 DOWNTO 0);  -- sfix48
  SIGNAL dout_1_re_tmp                    : signed(47 DOWNTO 0);  -- sfix48

BEGIN
  u_FTap_1 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_15,  -- sfix7
              addin => std_logic_vector(addin),  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout  -- sfix48
              );

  u_FTap_2 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_14,  -- sfix7
              addin => tapout,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_1  -- sfix48
              );

  u_FTap_3 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_13,  -- sfix7
              addin => tapout_1,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_2  -- sfix48
              );

  u_FTap_4 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_12,  -- sfix7
              addin => tapout_2,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_3  -- sfix48
              );

  u_FTap_5 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_11,  -- sfix7
              addin => tapout_3,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_4  -- sfix48
              );

  u_FTap_6 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_10,  -- sfix7
              addin => tapout_4,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_5  -- sfix48
              );

  u_FTap_7 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_9,  -- sfix7
              addin => tapout_5,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_6  -- sfix48
              );

  u_FTap_8 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_8,  -- sfix7
              addin => tapout_6,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_7  -- sfix48
              );

  u_FTap_9 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_7,  -- sfix7
              addin => tapout_7,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_8  -- sfix48
              );

  u_FTap_10 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_6,  -- sfix7
              addin => tapout_8,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_9  -- sfix48
              );

  u_FTap_11 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_5,  -- sfix7
              addin => tapout_9,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_10  -- sfix48
              );

  u_FTap_12 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_4,  -- sfix7
              addin => tapout_10,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_11  -- sfix48
              );

  u_FTap_13 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_3,  -- sfix7
              addin => tapout_11,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_12  -- sfix48
              );

  u_FTap_14 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_2,  -- sfix7
              addin => tapout_12,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_13  -- sfix48
              );

  u_FTap_15 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_1,  -- sfix7
              addin => tapout_13,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_14  -- sfix48
              );

  u_FTap_16 : myCorrelator_ip_src_FilterTapWvldIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix13
              coefIn_15 => coefIn_0,  -- sfix7
              addin => tapout_14,  -- sfix48
              multVld => multVld,
              syncReset => syncReset,
              tapout => tapout_15  -- sfix48
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSE 
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(2 DOWNTO 1) <= intdelay_reg(1 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  tapoutVld <= intdelay_reg(2);

  addin <= to_signed(0, 48);

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg_1 <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        intdelay_reg_1(0) <= dinRegVld;
        intdelay_reg_1(1) <= intdelay_reg_1(0);
      END IF;
    END IF;
  END PROCESS intdelay_1_process;

  multVld <= intdelay_reg_1(1);

  ZERO_OUT <= to_signed(0, 48);

  tapout_signed <= signed(tapout_15);

  
  muxOut <= ZERO_OUT WHEN tapoutVld = '0' ELSE
      tapout_signed;

  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(0, 48);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(0, 48);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

END rtl;

