-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip_src_Subsystem.vhd
-- Created: 2025-04-18 17:38:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip_src_Subsystem
-- Source Path: myCorrelator/myCorrelator/Subsystem
-- Hierarchy Level: 1
-- Model version: 8.511
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY myCorrelator_ip_src_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        real_in                           :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        imag_in                           :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        validIn                           :   IN    std_logic;
        energy                            :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29
        );
END myCorrelator_ip_src_Subsystem;


ARCHITECTURE rtl OF myCorrelator_ip_src_Subsystem IS

  -- Component Declarations
  COMPONENT myCorrelator_ip_src_fcn_delayLine
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          energyNew                       :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25
          validIn                         :   IN    std_logic;
          energyOld                       :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : myCorrelator_ip_src_fcn_delayLine
    USE ENTITY work.myCorrelator_ip_src_fcn_delayLine(rtl);

  -- Signals
  SIGNAL real_in_signed                   : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Product_out1                     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL imag_in_signed                   : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Product1_out1                    : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL energySample                     : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL energyOld                        : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL energyOld_signed                 : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL Sum_out1                         : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay3_bypass_delay              : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Delay3_reg                       : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL diffEnergy                       : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Data_Type_Conversion6_out1       : signed(27 DOWNTO 0);  -- sfix28
  SIGNAL energy_tmp                       : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL Delay8_bypass_delay              : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL Delay8_reg                       : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL energy_pre                       : signed(28 DOWNTO 0);  -- sfix29
  SIGNAL energy_pre_1                     : signed(27 DOWNTO 0);  -- sfix28

BEGIN
  u_fcn_delayLine : myCorrelator_ip_src_fcn_delayLine
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              energyNew => std_logic_vector(energySample),  -- sfix25
              validIn => validIn,
              energyOld => energyOld  -- sfix25
              );

  real_in_signed <= signed(real_in);

  Product_out1 <= real_in_signed * real_in_signed;

  imag_in_signed <= signed(imag_in);

  Product1_out1 <= imag_in_signed * imag_in_signed;

  energySample <= resize(Product_out1, 25) + resize(Product1_out1, 25);

  energyOld_signed <= signed(energyOld);

  Sum_out1 <= resize(energySample, 26) - resize(energyOld_signed, 26);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_bypass_delay <= to_signed(16#0000000#, 26);
        Delay3_reg <= to_signed(16#0000000#, 26);
      ELSIF enb = '1' AND validIn = '1' THEN
        Delay3_bypass_delay <= Delay3_reg;
        Delay3_reg <= Sum_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;

  
  diffEnergy <= Delay3_reg WHEN validIn = '1' ELSE
      Delay3_bypass_delay;

  Data_Type_Conversion6_out1 <= resize(diffEnergy, 28);

  Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_bypass_delay <= to_signed(16#00000000#, 29);
        Delay8_reg <= to_signed(16#00000000#, 29);
      ELSIF enb = '1' AND validIn = '1' THEN
        Delay8_bypass_delay <= Delay8_reg;
        Delay8_reg <= energy_tmp;
      END IF;
    END IF;
  END PROCESS Delay8_process;

  
  energy_pre <= Delay8_reg WHEN validIn = '1' ELSE
      Delay8_bypass_delay;

  energy_pre_1 <= energy_pre(27 DOWNTO 0);

  energy_tmp <= resize(Data_Type_Conversion6_out1, 29) + resize(energy_pre_1, 29);

  energy <= std_logic_vector(energy_tmp);

END rtl;

