-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\myCorrelator\myCorrelator_ip.vhd
-- Created: 2025-04-18 17:38:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: myCorrelator_ip
-- Source Path: myCorrelator_ip
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY myCorrelator_ip IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        inphase_in                        :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        quadrature_in                     :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        valid_in                          :   IN    std_logic;  -- ufix1
        complexCoefRealIn                 :   IN    std_logic_vector(95 DOWNTO 0);  -- ufix96
        complexCoefImagIn                 :   IN    std_logic_vector(95 DOWNTO 0);  -- ufix96
        detectedRepeat                    :   OUT   std_logic  -- ufix1
        );
END myCorrelator_ip;


ARCHITECTURE rtl OF myCorrelator_ip IS

  -- Component Declarations
  COMPONENT myCorrelator_ip_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT myCorrelator_ip_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          inphase_in                      :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          quadrature_in                   :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          valid_in                        :   IN    std_logic;  -- ufix1
          complexCoefRealIn_0             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_1             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_2             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_3             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_4             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_5             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_6             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_7             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_8             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_9             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_10            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_11            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_12            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_13            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_14            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefRealIn_15            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_0             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_1             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_2             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_3             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_4             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_5             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_6             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_7             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_8             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_9             :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_10            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_11            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_12            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_13            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_14            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          complexCoefImagIn_15            :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6
          ce_out                          :   OUT   std_logic;  -- ufix1
          detectedRepeat                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : myCorrelator_ip_reset_sync
    USE ENTITY work.myCorrelator_ip_reset_sync(rtl);

  FOR ALL : myCorrelator_ip_dut
    USE ENTITY work.myCorrelator_ip_dut(rtl);

  -- Signals
  SIGNAL reset                            : std_logic;
  SIGNAL dut_enable                       : std_logic;  -- ufix1
  SIGNAL inphase_in_unsigned              : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL inphase_in_sig                   : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL quadrature_in_unsigned           : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL quadrature_in_sig                : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL complexCoefRealIn_unsigned       : unsigned(95 DOWNTO 0);  -- ufix96
  SIGNAL complexCoefRealIn_slice          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_0_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_1        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_1_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_2        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_2_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_3        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_3_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_4        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_4_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_5        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_5_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_6        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_6_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_7        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_7_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_8        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_8_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_9        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_9_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_10       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_10_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_11       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_11_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_12       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_12_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_13       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_13_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_14       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_14_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefRealIn_slice_15       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefRealIn_15_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_unsigned       : unsigned(95 DOWNTO 0);  -- ufix96
  SIGNAL complexCoefImagIn_slice          : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_0_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_1        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_1_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_2        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_2_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_3        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_3_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_4        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_4_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_5        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_5_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_6        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_6_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_7        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_7_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_8        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_8_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_9        : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_9_sig          : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_10       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_10_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_11       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_11_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_12       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_12_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_13       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_13_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_14       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_14_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL complexCoefImagIn_slice_15       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL complexCoefImagIn_15_sig         : signed(5 DOWNTO 0);  -- sfix6
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL detectedRepeat_sig               : std_logic;  -- ufix1

BEGIN
  u_myCorrelator_ip_reset_sync_inst : myCorrelator_ip_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_cm,  -- ufix1
              reset_out => reset
              );

  u_myCorrelator_ip_dut_inst : myCorrelator_ip_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              dut_enable => dut_enable,  -- ufix1
              inphase_in => std_logic_vector(inphase_in_sig),  -- sfix12
              quadrature_in => std_logic_vector(quadrature_in_sig),  -- sfix12
              valid_in => valid_in,  -- ufix1
              complexCoefRealIn_0 => std_logic_vector(complexCoefRealIn_0_sig),  -- sfix6
              complexCoefRealIn_1 => std_logic_vector(complexCoefRealIn_1_sig),  -- sfix6
              complexCoefRealIn_2 => std_logic_vector(complexCoefRealIn_2_sig),  -- sfix6
              complexCoefRealIn_3 => std_logic_vector(complexCoefRealIn_3_sig),  -- sfix6
              complexCoefRealIn_4 => std_logic_vector(complexCoefRealIn_4_sig),  -- sfix6
              complexCoefRealIn_5 => std_logic_vector(complexCoefRealIn_5_sig),  -- sfix6
              complexCoefRealIn_6 => std_logic_vector(complexCoefRealIn_6_sig),  -- sfix6
              complexCoefRealIn_7 => std_logic_vector(complexCoefRealIn_7_sig),  -- sfix6
              complexCoefRealIn_8 => std_logic_vector(complexCoefRealIn_8_sig),  -- sfix6
              complexCoefRealIn_9 => std_logic_vector(complexCoefRealIn_9_sig),  -- sfix6
              complexCoefRealIn_10 => std_logic_vector(complexCoefRealIn_10_sig),  -- sfix6
              complexCoefRealIn_11 => std_logic_vector(complexCoefRealIn_11_sig),  -- sfix6
              complexCoefRealIn_12 => std_logic_vector(complexCoefRealIn_12_sig),  -- sfix6
              complexCoefRealIn_13 => std_logic_vector(complexCoefRealIn_13_sig),  -- sfix6
              complexCoefRealIn_14 => std_logic_vector(complexCoefRealIn_14_sig),  -- sfix6
              complexCoefRealIn_15 => std_logic_vector(complexCoefRealIn_15_sig),  -- sfix6
              complexCoefImagIn_0 => std_logic_vector(complexCoefImagIn_0_sig),  -- sfix6
              complexCoefImagIn_1 => std_logic_vector(complexCoefImagIn_1_sig),  -- sfix6
              complexCoefImagIn_2 => std_logic_vector(complexCoefImagIn_2_sig),  -- sfix6
              complexCoefImagIn_3 => std_logic_vector(complexCoefImagIn_3_sig),  -- sfix6
              complexCoefImagIn_4 => std_logic_vector(complexCoefImagIn_4_sig),  -- sfix6
              complexCoefImagIn_5 => std_logic_vector(complexCoefImagIn_5_sig),  -- sfix6
              complexCoefImagIn_6 => std_logic_vector(complexCoefImagIn_6_sig),  -- sfix6
              complexCoefImagIn_7 => std_logic_vector(complexCoefImagIn_7_sig),  -- sfix6
              complexCoefImagIn_8 => std_logic_vector(complexCoefImagIn_8_sig),  -- sfix6
              complexCoefImagIn_9 => std_logic_vector(complexCoefImagIn_9_sig),  -- sfix6
              complexCoefImagIn_10 => std_logic_vector(complexCoefImagIn_10_sig),  -- sfix6
              complexCoefImagIn_11 => std_logic_vector(complexCoefImagIn_11_sig),  -- sfix6
              complexCoefImagIn_12 => std_logic_vector(complexCoefImagIn_12_sig),  -- sfix6
              complexCoefImagIn_13 => std_logic_vector(complexCoefImagIn_13_sig),  -- sfix6
              complexCoefImagIn_14 => std_logic_vector(complexCoefImagIn_14_sig),  -- sfix6
              complexCoefImagIn_15 => std_logic_vector(complexCoefImagIn_15_sig),  -- sfix6
              ce_out => ce_out_sig,  -- ufix1
              detectedRepeat => detectedRepeat_sig  -- ufix1
              );

  dut_enable <= '1';

  inphase_in_unsigned <= unsigned(inphase_in);

  inphase_in_sig <= signed(inphase_in_unsigned);

  quadrature_in_unsigned <= unsigned(quadrature_in);

  quadrature_in_sig <= signed(quadrature_in_unsigned);

  complexCoefRealIn_unsigned <= unsigned(complexCoefRealIn);

  complexCoefRealIn_slice <= complexCoefRealIn_unsigned(5 DOWNTO 0);

  complexCoefRealIn_0_sig <= signed(complexCoefRealIn_slice);

  complexCoefRealIn_slice_1 <= complexCoefRealIn_unsigned(11 DOWNTO 6);

  complexCoefRealIn_1_sig <= signed(complexCoefRealIn_slice_1);

  complexCoefRealIn_slice_2 <= complexCoefRealIn_unsigned(17 DOWNTO 12);

  complexCoefRealIn_2_sig <= signed(complexCoefRealIn_slice_2);

  complexCoefRealIn_slice_3 <= complexCoefRealIn_unsigned(23 DOWNTO 18);

  complexCoefRealIn_3_sig <= signed(complexCoefRealIn_slice_3);

  complexCoefRealIn_slice_4 <= complexCoefRealIn_unsigned(29 DOWNTO 24);

  complexCoefRealIn_4_sig <= signed(complexCoefRealIn_slice_4);

  complexCoefRealIn_slice_5 <= complexCoefRealIn_unsigned(35 DOWNTO 30);

  complexCoefRealIn_5_sig <= signed(complexCoefRealIn_slice_5);

  complexCoefRealIn_slice_6 <= complexCoefRealIn_unsigned(41 DOWNTO 36);

  complexCoefRealIn_6_sig <= signed(complexCoefRealIn_slice_6);

  complexCoefRealIn_slice_7 <= complexCoefRealIn_unsigned(47 DOWNTO 42);

  complexCoefRealIn_7_sig <= signed(complexCoefRealIn_slice_7);

  complexCoefRealIn_slice_8 <= complexCoefRealIn_unsigned(53 DOWNTO 48);

  complexCoefRealIn_8_sig <= signed(complexCoefRealIn_slice_8);

  complexCoefRealIn_slice_9 <= complexCoefRealIn_unsigned(59 DOWNTO 54);

  complexCoefRealIn_9_sig <= signed(complexCoefRealIn_slice_9);

  complexCoefRealIn_slice_10 <= complexCoefRealIn_unsigned(65 DOWNTO 60);

  complexCoefRealIn_10_sig <= signed(complexCoefRealIn_slice_10);

  complexCoefRealIn_slice_11 <= complexCoefRealIn_unsigned(71 DOWNTO 66);

  complexCoefRealIn_11_sig <= signed(complexCoefRealIn_slice_11);

  complexCoefRealIn_slice_12 <= complexCoefRealIn_unsigned(77 DOWNTO 72);

  complexCoefRealIn_12_sig <= signed(complexCoefRealIn_slice_12);

  complexCoefRealIn_slice_13 <= complexCoefRealIn_unsigned(83 DOWNTO 78);

  complexCoefRealIn_13_sig <= signed(complexCoefRealIn_slice_13);

  complexCoefRealIn_slice_14 <= complexCoefRealIn_unsigned(89 DOWNTO 84);

  complexCoefRealIn_14_sig <= signed(complexCoefRealIn_slice_14);

  complexCoefRealIn_slice_15 <= complexCoefRealIn_unsigned(95 DOWNTO 90);

  complexCoefRealIn_15_sig <= signed(complexCoefRealIn_slice_15);

  complexCoefImagIn_unsigned <= unsigned(complexCoefImagIn);

  complexCoefImagIn_slice <= complexCoefImagIn_unsigned(5 DOWNTO 0);

  complexCoefImagIn_0_sig <= signed(complexCoefImagIn_slice);

  complexCoefImagIn_slice_1 <= complexCoefImagIn_unsigned(11 DOWNTO 6);

  complexCoefImagIn_1_sig <= signed(complexCoefImagIn_slice_1);

  complexCoefImagIn_slice_2 <= complexCoefImagIn_unsigned(17 DOWNTO 12);

  complexCoefImagIn_2_sig <= signed(complexCoefImagIn_slice_2);

  complexCoefImagIn_slice_3 <= complexCoefImagIn_unsigned(23 DOWNTO 18);

  complexCoefImagIn_3_sig <= signed(complexCoefImagIn_slice_3);

  complexCoefImagIn_slice_4 <= complexCoefImagIn_unsigned(29 DOWNTO 24);

  complexCoefImagIn_4_sig <= signed(complexCoefImagIn_slice_4);

  complexCoefImagIn_slice_5 <= complexCoefImagIn_unsigned(35 DOWNTO 30);

  complexCoefImagIn_5_sig <= signed(complexCoefImagIn_slice_5);

  complexCoefImagIn_slice_6 <= complexCoefImagIn_unsigned(41 DOWNTO 36);

  complexCoefImagIn_6_sig <= signed(complexCoefImagIn_slice_6);

  complexCoefImagIn_slice_7 <= complexCoefImagIn_unsigned(47 DOWNTO 42);

  complexCoefImagIn_7_sig <= signed(complexCoefImagIn_slice_7);

  complexCoefImagIn_slice_8 <= complexCoefImagIn_unsigned(53 DOWNTO 48);

  complexCoefImagIn_8_sig <= signed(complexCoefImagIn_slice_8);

  complexCoefImagIn_slice_9 <= complexCoefImagIn_unsigned(59 DOWNTO 54);

  complexCoefImagIn_9_sig <= signed(complexCoefImagIn_slice_9);

  complexCoefImagIn_slice_10 <= complexCoefImagIn_unsigned(65 DOWNTO 60);

  complexCoefImagIn_10_sig <= signed(complexCoefImagIn_slice_10);

  complexCoefImagIn_slice_11 <= complexCoefImagIn_unsigned(71 DOWNTO 66);

  complexCoefImagIn_11_sig <= signed(complexCoefImagIn_slice_11);

  complexCoefImagIn_slice_12 <= complexCoefImagIn_unsigned(77 DOWNTO 72);

  complexCoefImagIn_12_sig <= signed(complexCoefImagIn_slice_12);

  complexCoefImagIn_slice_13 <= complexCoefImagIn_unsigned(83 DOWNTO 78);

  complexCoefImagIn_13_sig <= signed(complexCoefImagIn_slice_13);

  complexCoefImagIn_slice_14 <= complexCoefImagIn_unsigned(89 DOWNTO 84);

  complexCoefImagIn_14_sig <= signed(complexCoefImagIn_slice_14);

  complexCoefImagIn_slice_15 <= complexCoefImagIn_unsigned(95 DOWNTO 90);

  complexCoefImagIn_15_sig <= signed(complexCoefImagIn_slice_15);

  reset_cm <=  NOT IPCORE_RESETN;

  detectedRepeat <= detectedRepeat_sig;

END rtl;

