-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor_72regs_2023b\monitor_72regs_pkg.vhd
-- Created: 2025-10-08 16:04:16
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE monitor_72regs_pkg IS
  TYPE vector_of_unsigned32 IS ARRAY (NATURAL RANGE <>) OF unsigned(31 DOWNTO 0);
END monitor_72regs_pkg;

