-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor_72regs_2023b\monitor_72regs_src_monitor_72regs_dut.vhd
-- Created: 2025-10-08 15:57:26
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: monitor_72regs_src_monitor_72regs_dut
-- Source Path: monitor_72regs_2023b/monitor_72regs_dut
-- Hierarchy Level: 0
-- Model version: 3.8
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY monitor_72regs_src_monitor_72regs_dut IS
  PORT( dataWriteAXI0                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI1                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI2                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI3                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI4                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI5                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI6                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI7                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead9                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead10                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead11                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead12                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead13                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead14                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead15                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI8                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI9                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI10                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI11                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI12                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI13                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI14                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI15                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI16                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI17                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI18                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI19                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI20                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI21                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI22                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI23                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead16                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead17                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead18                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead19                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead20                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead21                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead22                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataRead23                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI24                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI25                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI26                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI27                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI28                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI29                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI30                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI31                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI32                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI33                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI34                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI35                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI36                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI37                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI38                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI39                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI40                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI41                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI42                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI43                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI44                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI45                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI46                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI47                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI48                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI49                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI50                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI51                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI52                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI53                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI54                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI55                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI56                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI57                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI58                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI59                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI60                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI61                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI62                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI63                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI64                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI65                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI66                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI67                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI68                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI69                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI70                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWriteAXI71                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite4                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite5                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite6                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite7                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite8                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite9                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite10                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite11                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite12                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite13                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite14                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite15                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI8                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI9                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI10                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI11                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI12                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI13                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI14                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI15                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite16                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite17                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite18                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite19                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite20                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite21                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite22                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite23                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI16                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI17                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI18                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI19                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI20                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI21                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI22                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataReadAXI23                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite24                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite25                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite26                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite27                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite28                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite29                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite30                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite31                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite32                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite33                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite34                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite35                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite36                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite37                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite38                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite39                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite40                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite41                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite42                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite43                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite44                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite45                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite46                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite47                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite48                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite49                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite50                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite51                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite52                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite53                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite54                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite55                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite56                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite57                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite58                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite59                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite60                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite61                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite62                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite63                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite64                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite65                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite66                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite67                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite68                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite69                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite70                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        dataWrite71                       :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END monitor_72regs_src_monitor_72regs_dut;


ARCHITECTURE rtl OF monitor_72regs_src_monitor_72regs_dut IS

  -- Component Declarations
  COMPONENT monitor_72regs_src_MATLAB_Function
    PORT( dataWriteAXI0                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI1                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI2                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI3                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI4                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI5                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI6                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI7                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI8                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI9                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI10                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI11                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI12                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI13                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI14                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI15                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI16                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI17                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI18                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI19                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI20                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI21                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI22                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI23                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI24                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI25                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI26                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI27                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI28                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI29                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI30                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI31                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI32                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI33                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI34                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI35                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI36                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI37                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI38                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI39                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI40                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI41                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI42                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI43                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI44                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI45                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI46                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI47                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI48                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI49                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI50                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI51                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI52                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI53                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI54                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI55                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI56                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI57                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI58                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI59                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI60                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI61                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI62                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI63                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI71                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI70                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI69                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI68                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI67                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI66                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI65                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWriteAXI64                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead0                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead8                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead9                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead10                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead11                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead12                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead13                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead14                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead15                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead16                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead17                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead18                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead19                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead20                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead21                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead22                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataRead23                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite8                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite9                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite10                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite11                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite12                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite13                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite14                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite15                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite16                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite17                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite18                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite19                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite20                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite21                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite22                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite23                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite24                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite25                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite26                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite27                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite28                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite29                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite30                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite31                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite32                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite33                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite34                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite35                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite36                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite37                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite38                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite39                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite40                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite41                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite42                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite43                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite44                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite45                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite46                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite47                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite48                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite49                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite50                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite51                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite52                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite53                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite54                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite55                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite56                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite57                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite58                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite59                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite60                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite61                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite62                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite63                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite71                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite70                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite69                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite68                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite67                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite66                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite65                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataWrite64                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI0                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI1                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI2                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI3                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI4                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI5                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI6                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI7                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI8                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI9                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI10                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI11                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI12                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI13                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI14                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI15                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI16                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI17                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI18                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI19                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI20                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI21                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI22                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          dataReadAXI23                   :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : monitor_72regs_src_MATLAB_Function
    USE ENTITY work.monitor_72regs_src_MATLAB_Function(rtl);

  -- Signals
  SIGNAL dataWrite0_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite1_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite2_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite3_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite4_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite5_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite6_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite7_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite8_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite9_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite10_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite11_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite12_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite13_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite14_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite15_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite16_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite17_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite18_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite19_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite20_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite21_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite22_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite23_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite24_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite25_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite26_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite27_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite28_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite29_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite30_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite31_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite32_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite33_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite34_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite35_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite36_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite37_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite38_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite39_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite40_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite41_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite42_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite43_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite44_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite45_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite46_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite47_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite48_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite49_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite50_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite51_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite52_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite53_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite54_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite55_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite56_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite57_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite58_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite59_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite60_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite61_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite62_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite63_tmp                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite71_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite70_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite69_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite68_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite67_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite66_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite65_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite64_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI0_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI1_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI2_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI3_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI4_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI5_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI6_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI7_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI8_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI9_tmp                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI10_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI11_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI12_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI13_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI14_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI15_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI16_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI17_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI18_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI19_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI20_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI21_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI22_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI23_tmp                : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_MATLAB_Function : monitor_72regs_src_MATLAB_Function
    PORT MAP( dataWriteAXI0 => dataWriteAXI0,  -- uint32
              dataWriteAXI1 => dataWriteAXI1,  -- uint32
              dataWriteAXI2 => dataWriteAXI2,  -- uint32
              dataWriteAXI3 => dataWriteAXI3,  -- uint32
              dataWriteAXI4 => dataWriteAXI4,  -- uint32
              dataWriteAXI5 => dataWriteAXI5,  -- uint32
              dataWriteAXI6 => dataWriteAXI6,  -- uint32
              dataWriteAXI7 => dataWriteAXI7,  -- uint32
              dataWriteAXI8 => dataWriteAXI8,  -- uint32
              dataWriteAXI9 => dataWriteAXI9,  -- uint32
              dataWriteAXI10 => dataWriteAXI10,  -- uint32
              dataWriteAXI11 => dataWriteAXI11,  -- uint32
              dataWriteAXI12 => dataWriteAXI12,  -- uint32
              dataWriteAXI13 => dataWriteAXI13,  -- uint32
              dataWriteAXI14 => dataWriteAXI14,  -- uint32
              dataWriteAXI15 => dataWriteAXI15,  -- uint32
              dataWriteAXI16 => dataWriteAXI16,  -- uint32
              dataWriteAXI17 => dataWriteAXI17,  -- uint32
              dataWriteAXI18 => dataWriteAXI18,  -- uint32
              dataWriteAXI19 => dataWriteAXI19,  -- uint32
              dataWriteAXI20 => dataWriteAXI20,  -- uint32
              dataWriteAXI21 => dataWriteAXI21,  -- uint32
              dataWriteAXI22 => dataWriteAXI22,  -- uint32
              dataWriteAXI23 => dataWriteAXI23,  -- uint32
              dataWriteAXI24 => dataWriteAXI24,  -- uint32
              dataWriteAXI25 => dataWriteAXI25,  -- uint32
              dataWriteAXI26 => dataWriteAXI26,  -- uint32
              dataWriteAXI27 => dataWriteAXI27,  -- uint32
              dataWriteAXI28 => dataWriteAXI28,  -- uint32
              dataWriteAXI29 => dataWriteAXI29,  -- uint32
              dataWriteAXI30 => dataWriteAXI30,  -- uint32
              dataWriteAXI31 => dataWriteAXI31,  -- uint32
              dataWriteAXI32 => dataWriteAXI32,  -- uint32
              dataWriteAXI33 => dataWriteAXI33,  -- uint32
              dataWriteAXI34 => dataWriteAXI34,  -- uint32
              dataWriteAXI35 => dataWriteAXI35,  -- uint32
              dataWriteAXI36 => dataWriteAXI36,  -- uint32
              dataWriteAXI37 => dataWriteAXI37,  -- uint32
              dataWriteAXI38 => dataWriteAXI38,  -- uint32
              dataWriteAXI39 => dataWriteAXI39,  -- uint32
              dataWriteAXI40 => dataWriteAXI40,  -- uint32
              dataWriteAXI41 => dataWriteAXI41,  -- uint32
              dataWriteAXI42 => dataWriteAXI42,  -- uint32
              dataWriteAXI43 => dataWriteAXI43,  -- uint32
              dataWriteAXI44 => dataWriteAXI44,  -- uint32
              dataWriteAXI45 => dataWriteAXI45,  -- uint32
              dataWriteAXI46 => dataWriteAXI46,  -- uint32
              dataWriteAXI47 => dataWriteAXI47,  -- uint32
              dataWriteAXI48 => dataWriteAXI48,  -- uint32
              dataWriteAXI49 => dataWriteAXI49,  -- uint32
              dataWriteAXI50 => dataWriteAXI50,  -- uint32
              dataWriteAXI51 => dataWriteAXI51,  -- uint32
              dataWriteAXI52 => dataWriteAXI52,  -- uint32
              dataWriteAXI53 => dataWriteAXI53,  -- uint32
              dataWriteAXI54 => dataWriteAXI54,  -- uint32
              dataWriteAXI55 => dataWriteAXI55,  -- uint32
              dataWriteAXI56 => dataWriteAXI56,  -- uint32
              dataWriteAXI57 => dataWriteAXI57,  -- uint32
              dataWriteAXI58 => dataWriteAXI58,  -- uint32
              dataWriteAXI59 => dataWriteAXI59,  -- uint32
              dataWriteAXI60 => dataWriteAXI60,  -- uint32
              dataWriteAXI61 => dataWriteAXI61,  -- uint32
              dataWriteAXI62 => dataWriteAXI62,  -- uint32
              dataWriteAXI63 => dataWriteAXI63,  -- uint32
              dataWriteAXI71 => dataWriteAXI64,  -- uint32
              dataWriteAXI70 => dataWriteAXI65,  -- uint32
              dataWriteAXI69 => dataWriteAXI66,  -- uint32
              dataWriteAXI68 => dataWriteAXI67,  -- uint32
              dataWriteAXI67 => dataWriteAXI68,  -- uint32
              dataWriteAXI66 => dataWriteAXI69,  -- uint32
              dataWriteAXI65 => dataWriteAXI70,  -- uint32
              dataWriteAXI64 => dataWriteAXI71,  -- uint32
              dataRead0 => dataRead0,  -- uint32
              dataRead1 => dataRead1,  -- uint32
              dataRead2 => dataRead2,  -- uint32
              dataRead3 => dataRead3,  -- uint32
              dataRead4 => dataRead4,  -- uint32
              dataRead5 => dataRead5,  -- uint32
              dataRead6 => dataRead6,  -- uint32
              dataRead7 => dataRead7,  -- uint32
              dataRead8 => dataRead8,  -- uint32
              dataRead9 => dataRead9,  -- uint32
              dataRead10 => dataRead10,  -- uint32
              dataRead11 => dataRead11,  -- uint32
              dataRead12 => dataRead12,  -- uint32
              dataRead13 => dataRead13,  -- uint32
              dataRead14 => dataRead14,  -- uint32
              dataRead15 => dataRead15,  -- uint32
              dataRead16 => dataRead16,  -- uint32
              dataRead17 => dataRead17,  -- uint32
              dataRead18 => dataRead18,  -- uint32
              dataRead19 => dataRead19,  -- uint32
              dataRead20 => dataRead20,  -- uint32
              dataRead21 => dataRead21,  -- uint32
              dataRead22 => dataRead22,  -- uint32
              dataRead23 => dataRead23,  -- uint32
              dataWrite0 => dataWrite0_tmp,  -- uint32
              dataWrite1 => dataWrite1_tmp,  -- uint32
              dataWrite2 => dataWrite2_tmp,  -- uint32
              dataWrite3 => dataWrite3_tmp,  -- uint32
              dataWrite4 => dataWrite4_tmp,  -- uint32
              dataWrite5 => dataWrite5_tmp,  -- uint32
              dataWrite6 => dataWrite6_tmp,  -- uint32
              dataWrite7 => dataWrite7_tmp,  -- uint32
              dataWrite8 => dataWrite8_tmp,  -- uint32
              dataWrite9 => dataWrite9_tmp,  -- uint32
              dataWrite10 => dataWrite10_tmp,  -- uint32
              dataWrite11 => dataWrite11_tmp,  -- uint32
              dataWrite12 => dataWrite12_tmp,  -- uint32
              dataWrite13 => dataWrite13_tmp,  -- uint32
              dataWrite14 => dataWrite14_tmp,  -- uint32
              dataWrite15 => dataWrite15_tmp,  -- uint32
              dataWrite16 => dataWrite16_tmp,  -- uint32
              dataWrite17 => dataWrite17_tmp,  -- uint32
              dataWrite18 => dataWrite18_tmp,  -- uint32
              dataWrite19 => dataWrite19_tmp,  -- uint32
              dataWrite20 => dataWrite20_tmp,  -- uint32
              dataWrite21 => dataWrite21_tmp,  -- uint32
              dataWrite22 => dataWrite22_tmp,  -- uint32
              dataWrite23 => dataWrite23_tmp,  -- uint32
              dataWrite24 => dataWrite24_tmp,  -- uint32
              dataWrite25 => dataWrite25_tmp,  -- uint32
              dataWrite26 => dataWrite26_tmp,  -- uint32
              dataWrite27 => dataWrite27_tmp,  -- uint32
              dataWrite28 => dataWrite28_tmp,  -- uint32
              dataWrite29 => dataWrite29_tmp,  -- uint32
              dataWrite30 => dataWrite30_tmp,  -- uint32
              dataWrite31 => dataWrite31_tmp,  -- uint32
              dataWrite32 => dataWrite32_tmp,  -- uint32
              dataWrite33 => dataWrite33_tmp,  -- uint32
              dataWrite34 => dataWrite34_tmp,  -- uint32
              dataWrite35 => dataWrite35_tmp,  -- uint32
              dataWrite36 => dataWrite36_tmp,  -- uint32
              dataWrite37 => dataWrite37_tmp,  -- uint32
              dataWrite38 => dataWrite38_tmp,  -- uint32
              dataWrite39 => dataWrite39_tmp,  -- uint32
              dataWrite40 => dataWrite40_tmp,  -- uint32
              dataWrite41 => dataWrite41_tmp,  -- uint32
              dataWrite42 => dataWrite42_tmp,  -- uint32
              dataWrite43 => dataWrite43_tmp,  -- uint32
              dataWrite44 => dataWrite44_tmp,  -- uint32
              dataWrite45 => dataWrite45_tmp,  -- uint32
              dataWrite46 => dataWrite46_tmp,  -- uint32
              dataWrite47 => dataWrite47_tmp,  -- uint32
              dataWrite48 => dataWrite48_tmp,  -- uint32
              dataWrite49 => dataWrite49_tmp,  -- uint32
              dataWrite50 => dataWrite50_tmp,  -- uint32
              dataWrite51 => dataWrite51_tmp,  -- uint32
              dataWrite52 => dataWrite52_tmp,  -- uint32
              dataWrite53 => dataWrite53_tmp,  -- uint32
              dataWrite54 => dataWrite54_tmp,  -- uint32
              dataWrite55 => dataWrite55_tmp,  -- uint32
              dataWrite56 => dataWrite56_tmp,  -- uint32
              dataWrite57 => dataWrite57_tmp,  -- uint32
              dataWrite58 => dataWrite58_tmp,  -- uint32
              dataWrite59 => dataWrite59_tmp,  -- uint32
              dataWrite60 => dataWrite60_tmp,  -- uint32
              dataWrite61 => dataWrite61_tmp,  -- uint32
              dataWrite62 => dataWrite62_tmp,  -- uint32
              dataWrite63 => dataWrite63_tmp,  -- uint32
              dataWrite71 => dataWrite71_1,  -- uint32
              dataWrite70 => dataWrite70_1,  -- uint32
              dataWrite69 => dataWrite69_1,  -- uint32
              dataWrite68 => dataWrite68_1,  -- uint32
              dataWrite67 => dataWrite67_1,  -- uint32
              dataWrite66 => dataWrite66_1,  -- uint32
              dataWrite65 => dataWrite65_1,  -- uint32
              dataWrite64 => dataWrite64_1,  -- uint32
              dataReadAXI0 => dataReadAXI0_tmp,  -- uint32
              dataReadAXI1 => dataReadAXI1_tmp,  -- uint32
              dataReadAXI2 => dataReadAXI2_tmp,  -- uint32
              dataReadAXI3 => dataReadAXI3_tmp,  -- uint32
              dataReadAXI4 => dataReadAXI4_tmp,  -- uint32
              dataReadAXI5 => dataReadAXI5_tmp,  -- uint32
              dataReadAXI6 => dataReadAXI6_tmp,  -- uint32
              dataReadAXI7 => dataReadAXI7_tmp,  -- uint32
              dataReadAXI8 => dataReadAXI8_tmp,  -- uint32
              dataReadAXI9 => dataReadAXI9_tmp,  -- uint32
              dataReadAXI10 => dataReadAXI10_tmp,  -- uint32
              dataReadAXI11 => dataReadAXI11_tmp,  -- uint32
              dataReadAXI12 => dataReadAXI12_tmp,  -- uint32
              dataReadAXI13 => dataReadAXI13_tmp,  -- uint32
              dataReadAXI14 => dataReadAXI14_tmp,  -- uint32
              dataReadAXI15 => dataReadAXI15_tmp,  -- uint32
              dataReadAXI16 => dataReadAXI16_tmp,  -- uint32
              dataReadAXI17 => dataReadAXI17_tmp,  -- uint32
              dataReadAXI18 => dataReadAXI18_tmp,  -- uint32
              dataReadAXI19 => dataReadAXI19_tmp,  -- uint32
              dataReadAXI20 => dataReadAXI20_tmp,  -- uint32
              dataReadAXI21 => dataReadAXI21_tmp,  -- uint32
              dataReadAXI22 => dataReadAXI22_tmp,  -- uint32
              dataReadAXI23 => dataReadAXI23_tmp  -- uint32
              );

  dataWrite0 <= dataWrite0_tmp;

  dataWrite1 <= dataWrite1_tmp;

  dataWrite2 <= dataWrite2_tmp;

  dataWrite3 <= dataWrite3_tmp;

  dataWrite4 <= dataWrite4_tmp;

  dataWrite5 <= dataWrite5_tmp;

  dataWrite6 <= dataWrite6_tmp;

  dataWrite7 <= dataWrite7_tmp;

  dataReadAXI0 <= dataReadAXI0_tmp;

  dataReadAXI1 <= dataReadAXI1_tmp;

  dataReadAXI2 <= dataReadAXI2_tmp;

  dataReadAXI3 <= dataReadAXI3_tmp;

  dataReadAXI4 <= dataReadAXI4_tmp;

  dataReadAXI5 <= dataReadAXI5_tmp;

  dataReadAXI6 <= dataReadAXI6_tmp;

  dataReadAXI7 <= dataReadAXI7_tmp;

  dataWrite8 <= dataWrite8_tmp;

  dataWrite9 <= dataWrite9_tmp;

  dataWrite10 <= dataWrite10_tmp;

  dataWrite11 <= dataWrite11_tmp;

  dataWrite12 <= dataWrite12_tmp;

  dataWrite13 <= dataWrite13_tmp;

  dataWrite14 <= dataWrite14_tmp;

  dataWrite15 <= dataWrite15_tmp;

  dataReadAXI8 <= dataReadAXI8_tmp;

  dataReadAXI9 <= dataReadAXI9_tmp;

  dataReadAXI10 <= dataReadAXI10_tmp;

  dataReadAXI11 <= dataReadAXI11_tmp;

  dataReadAXI12 <= dataReadAXI12_tmp;

  dataReadAXI13 <= dataReadAXI13_tmp;

  dataReadAXI14 <= dataReadAXI14_tmp;

  dataReadAXI15 <= dataReadAXI15_tmp;

  dataWrite16 <= dataWrite16_tmp;

  dataWrite17 <= dataWrite17_tmp;

  dataWrite18 <= dataWrite18_tmp;

  dataWrite19 <= dataWrite19_tmp;

  dataWrite20 <= dataWrite20_tmp;

  dataWrite21 <= dataWrite21_tmp;

  dataWrite22 <= dataWrite22_tmp;

  dataWrite23 <= dataWrite23_tmp;

  dataReadAXI16 <= dataReadAXI16_tmp;

  dataReadAXI17 <= dataReadAXI17_tmp;

  dataReadAXI18 <= dataReadAXI18_tmp;

  dataReadAXI19 <= dataReadAXI19_tmp;

  dataReadAXI20 <= dataReadAXI20_tmp;

  dataReadAXI21 <= dataReadAXI21_tmp;

  dataReadAXI22 <= dataReadAXI22_tmp;

  dataReadAXI23 <= dataReadAXI23_tmp;

  dataWrite24 <= dataWrite24_tmp;

  dataWrite25 <= dataWrite25_tmp;

  dataWrite26 <= dataWrite26_tmp;

  dataWrite27 <= dataWrite27_tmp;

  dataWrite28 <= dataWrite28_tmp;

  dataWrite29 <= dataWrite29_tmp;

  dataWrite30 <= dataWrite30_tmp;

  dataWrite31 <= dataWrite31_tmp;

  dataWrite32 <= dataWrite32_tmp;

  dataWrite33 <= dataWrite33_tmp;

  dataWrite34 <= dataWrite34_tmp;

  dataWrite35 <= dataWrite35_tmp;

  dataWrite36 <= dataWrite36_tmp;

  dataWrite37 <= dataWrite37_tmp;

  dataWrite38 <= dataWrite38_tmp;

  dataWrite39 <= dataWrite39_tmp;

  dataWrite40 <= dataWrite40_tmp;

  dataWrite41 <= dataWrite41_tmp;

  dataWrite42 <= dataWrite42_tmp;

  dataWrite43 <= dataWrite43_tmp;

  dataWrite44 <= dataWrite44_tmp;

  dataWrite45 <= dataWrite45_tmp;

  dataWrite46 <= dataWrite46_tmp;

  dataWrite47 <= dataWrite47_tmp;

  dataWrite48 <= dataWrite48_tmp;

  dataWrite49 <= dataWrite49_tmp;

  dataWrite50 <= dataWrite50_tmp;

  dataWrite51 <= dataWrite51_tmp;

  dataWrite52 <= dataWrite52_tmp;

  dataWrite53 <= dataWrite53_tmp;

  dataWrite54 <= dataWrite54_tmp;

  dataWrite55 <= dataWrite55_tmp;

  dataWrite56 <= dataWrite56_tmp;

  dataWrite57 <= dataWrite57_tmp;

  dataWrite58 <= dataWrite58_tmp;

  dataWrite59 <= dataWrite59_tmp;

  dataWrite60 <= dataWrite60_tmp;

  dataWrite61 <= dataWrite61_tmp;

  dataWrite62 <= dataWrite62_tmp;

  dataWrite63 <= dataWrite63_tmp;

  dataWrite64 <= dataWrite71_1;

  dataWrite65 <= dataWrite70_1;

  dataWrite66 <= dataWrite69_1;

  dataWrite67 <= dataWrite68_1;

  dataWrite68 <= dataWrite67_1;

  dataWrite69 <= dataWrite66_1;

  dataWrite70 <= dataWrite65_1;

  dataWrite71 <= dataWrite64_1;

END rtl;

