-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_CordicKernelMag.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_src_CordicKernelMag
-- Source Path: phaseCorrectionCordic/Phase Correction Cordic IP DUT/HDL_CMA_core/CordicKernelMag
-- Hierarchy Level: 2
-- Model version: 8.574
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY phaseCorrectionCordic_src_CordicKernelMag IS
  PORT( xin                               :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
        yin                               :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
        zin                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En20
        lut_value                         :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En20
        idx                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        xout                              :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        yout                              :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        zout                              :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En20
        );
END phaseCorrectionCordic_src_CordicKernelMag;


ARCHITECTURE rtl OF phaseCorrectionCordic_src_CordicKernelMag IS

  -- Signals
  SIGNAL yin_signed                       : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yLessThanZero                    : std_logic;
  SIGNAL xin_signed                       : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL idx_unsigned                     : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL yShifted                         : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xout2                            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xout1                            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xout_tmp                         : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xShifted                         : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout2                            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout1                            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout_tmp                         : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin_signed                       : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value_unsigned               : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL ZAdder_add_cast                  : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL zout2                            : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL ZSub_sub_cast                    : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL zout1                            : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL zout_tmp                         : signed(20 DOWNTO 0);  -- sfix21_En20

BEGIN
  yin_signed <= signed(yin);

  
  yLessThanZero <= '1' WHEN yin_signed < to_signed(16#00000#, 19) ELSE
      '0';

  xin_signed <= signed(xin);

  idx_unsigned <= unsigned(idx);

  yShifted <= SHIFT_RIGHT(yin_signed, to_integer(idx_unsigned));

  xout2 <= xin_signed + yShifted;

  xout1 <= xin_signed - yShifted;

  
  xout_tmp <= xout2 WHEN yLessThanZero = '0' ELSE
      xout1;

  xout <= std_logic_vector(xout_tmp);

  xShifted <= SHIFT_RIGHT(xin_signed, to_integer(idx_unsigned));

  yout2 <= yin_signed - xShifted;

  yout1 <= yin_signed + xShifted;

  
  yout_tmp <= yout2 WHEN yLessThanZero = '0' ELSE
      yout1;

  yout <= std_logic_vector(yout_tmp);

  zin_signed <= signed(zin);

  lut_value_unsigned <= unsigned(lut_value);

  ZAdder_add_cast <= signed(resize(lut_value_unsigned, 21));
  zout2 <= zin_signed + ZAdder_add_cast;

  ZSub_sub_cast <= signed(resize(lut_value_unsigned, 21));
  zout1 <= zin_signed - ZSub_sub_cast;

  
  zout_tmp <= zout2 WHEN yLessThanZero = '0' ELSE
      zout1;

  zout <= std_logic_vector(zout_tmp);

END rtl;

