-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic.vhd
-- Created: 2025-02-23 12:06:09
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic
-- Source Path: phaseCorrectionCordic
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY phaseCorrectionCordic IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        a                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18
        b                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18
        inphaseIn                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        quadratureIn                      :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        angleBias                         :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21
        inphaseOut                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        quadratureOut                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        magnitudeXcorr                    :   OUT   std_logic_vector(18 DOWNTO 0)  -- ufix19
        );
END phaseCorrectionCordic;


ARCHITECTURE rtl OF phaseCorrectionCordic IS

  -- Component Declarations
  COMPONENT phaseCorrectionCordic_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT phaseCorrectionCordic_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          a                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          b                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          inphaseIn                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          quadratureIn                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          angleBias                       :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21_En21
          ce_out                          :   OUT   std_logic;  -- ufix1
          inphaseOut                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          quadratureOut                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          magnitudeXcorr                  :   OUT   std_logic_vector(18 DOWNTO 0)  -- sfix19
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : phaseCorrectionCordic_reset_sync
    USE ENTITY work.phaseCorrectionCordic_reset_sync(rtl);

  FOR ALL : phaseCorrectionCordic_dut
    USE ENTITY work.phaseCorrectionCordic_dut(rtl);

  -- Signals
  SIGNAL reset                            : std_logic;
  SIGNAL dut_enable                       : std_logic;  -- ufix1
  SIGNAL a_unsigned                       : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL a_sig                            : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL b_unsigned                       : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL b_sig                            : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL inphaseIn_unsigned               : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL inphaseIn_sig                    : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL quadratureIn_unsigned            : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL quadratureIn_sig                 : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL angleBias_unsigned               : unsigned(20 DOWNTO 0);  -- ufix21
  SIGNAL angleBias_sig                    : unsigned(20 DOWNTO 0);  -- ufix21_En21
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL inphaseOut_sig                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL quadratureOut_sig                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL magnitudeXcorr_sig               : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL inphaseOut_sig_signed            : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL inphaseOut_tmp                   : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL quadratureOut_sig_signed         : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL quadratureOut_tmp                : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL magnitudeXcorr_sig_signed        : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL magnitudeXcorr_tmp               : unsigned(18 DOWNTO 0);  -- ufix19

BEGIN
  u_phaseCorrectionCordic_reset_sync_inst : phaseCorrectionCordic_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_cm,  -- ufix1
              reset_out => reset
              );

  u_phaseCorrectionCordic_dut_inst : phaseCorrectionCordic_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              dut_enable => dut_enable,  -- ufix1
              a => std_logic_vector(a_sig),  -- sfix18
              b => std_logic_vector(b_sig),  -- sfix18
              inphaseIn => std_logic_vector(inphaseIn_sig),  -- sfix16
              quadratureIn => std_logic_vector(quadratureIn_sig),  -- sfix16
              angleBias => std_logic_vector(angleBias_sig),  -- ufix21_En21
              ce_out => ce_out_sig,  -- ufix1
              inphaseOut => inphaseOut_sig,  -- sfix16
              quadratureOut => quadratureOut_sig,  -- sfix16
              magnitudeXcorr => magnitudeXcorr_sig  -- sfix19
              );

  dut_enable <= '1';

  a_unsigned <= unsigned(a);

  a_sig <= signed(a_unsigned);

  b_unsigned <= unsigned(b);

  b_sig <= signed(b_unsigned);

  inphaseIn_unsigned <= unsigned(inphaseIn);

  inphaseIn_sig <= signed(inphaseIn_unsigned);

  quadratureIn_unsigned <= unsigned(quadratureIn);

  quadratureIn_sig <= signed(quadratureIn_unsigned);

  angleBias_unsigned <= unsigned(angleBias);

  angleBias_sig <= angleBias_unsigned;

  reset_cm <=  NOT IPCORE_RESETN;

  inphaseOut_sig_signed <= signed(inphaseOut_sig);

  inphaseOut_tmp <= unsigned(inphaseOut_sig_signed);

  inphaseOut <= std_logic_vector(inphaseOut_tmp);

  quadratureOut_sig_signed <= signed(quadratureOut_sig);

  quadratureOut_tmp <= unsigned(quadratureOut_sig_signed);

  quadratureOut <= std_logic_vector(quadratureOut_tmp);

  magnitudeXcorr_sig_signed <= signed(magnitudeXcorr_sig);

  magnitudeXcorr_tmp <= unsigned(magnitudeXcorr_sig_signed);

  magnitudeXcorr <= std_logic_vector(magnitudeXcorr_tmp);

END rtl;

