-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_fcn_IQconversion.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_src_fcn_IQconversion
-- Source Path: phaseCorrectionCordic/Phase Correction Cordic IP DUT/fcn_IQconversion
-- Hierarchy Level: 1
-- Model version: 8.574
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY phaseCorrectionCordic_src_fcn_IQconversion IS
  PORT( aIn                               :   IN    std_logic_vector(34 DOWNTO 0);  -- sfix35_En16
        bIn                               :   IN    std_logic_vector(34 DOWNTO 0);  -- sfix35_En16
        aInConv                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        bInConv                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END phaseCorrectionCordic_src_fcn_IQconversion;


ARCHITECTURE rtl OF phaseCorrectionCordic_src_fcn_IQconversion IS

  -- Signals
  SIGNAL aIn_signed                       : signed(34 DOWNTO 0);  -- sfix35_En16
  SIGNAL bIn_signed                       : signed(34 DOWNTO 0);  -- sfix35_En16
  SIGNAL aInConv_tmp                      : signed(15 DOWNTO 0);  -- int16
  SIGNAL bInConv_tmp                      : signed(15 DOWNTO 0);  -- int16
  SIGNAL aInSliced                        : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL bInSliced                        : unsigned(15 DOWNTO 0);  -- ufix16

BEGIN
  aIn_signed <= signed(aIn);

  bIn_signed <= signed(bIn);

  --    %% Parameters
  --    %% Set outputs
  aInSliced <= unsigned(aIn_signed(31 DOWNTO 16));
  bInSliced <= unsigned(bIn_signed(31 DOWNTO 16));
  aInConv_tmp <= signed(aInSliced);
  bInConv_tmp <= signed(bInSliced);

  aInConv <= std_logic_vector(aInConv_tmp);

  bInConv <= std_logic_vector(bInConv_tmp);

END rtl;

