-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- inphaseOut                    ce_out        1
-- quadratureOut                 ce_out        1
-- magnitudeXcorr                ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT
-- Source Path: phaseCorrectionCordic/Phase Correction Cordic IP DUT
-- Hierarchy Level: 0
-- Model version: 8.574
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        a                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        b                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        inphaseIn                         :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        quadratureIn                      :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        angleBias                         :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21_En21
        ce_out                            :   OUT   std_logic;
        inphaseOut                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        quadratureOut                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        magnitudeXcorr                    :   OUT   std_logic_vector(18 DOWNTO 0)  -- sfix19
        );
END phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT;


ARCHITECTURE rtl OF phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT IS

  -- Component Declarations
  COMPONENT phaseCorrectionCordic_src_HDL_CMA_core
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_re                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          In_im                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          validIn                         :   IN    std_logic;
          magnitude                       :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
          angle                           :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En20
          );
  END COMPONENT;

  COMPONENT phaseCorrectionCordic_src_Cosine_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21_En21
          x                               :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En16
          );
  END COMPONENT;

  COMPONENT phaseCorrectionCordic_src_Sine_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21_En21
          x                               :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En16
          );
  END COMPONENT;

  COMPONENT phaseCorrectionCordic_src_Subsystem1
    PORT( inPhaseIn                       :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          quadratureIn                    :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          aNormalized                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          bNormalized                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          inphaseOut                      :   OUT   std_logic_vector(34 DOWNTO 0);  -- sfix35_En16
          quadratureOut                   :   OUT   std_logic_vector(34 DOWNTO 0)  -- sfix35_En16
          );
  END COMPONENT;

  COMPONENT phaseCorrectionCordic_src_fcn_IQconversion
    PORT( aIn                             :   IN    std_logic_vector(34 DOWNTO 0);  -- sfix35_En16
          bIn                             :   IN    std_logic_vector(34 DOWNTO 0);  -- sfix35_En16
          aInConv                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          bInConv                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : phaseCorrectionCordic_src_HDL_CMA_core
    USE ENTITY work.phaseCorrectionCordic_src_HDL_CMA_core(rtl);

  FOR ALL : phaseCorrectionCordic_src_Cosine_HDL_Optimized
    USE ENTITY work.phaseCorrectionCordic_src_Cosine_HDL_Optimized(rtl);

  FOR ALL : phaseCorrectionCordic_src_Sine_HDL_Optimized
    USE ENTITY work.phaseCorrectionCordic_src_Sine_HDL_Optimized(rtl);

  FOR ALL : phaseCorrectionCordic_src_Subsystem1
    USE ENTITY work.phaseCorrectionCordic_src_Subsystem1(rtl);

  FOR ALL : phaseCorrectionCordic_src_fcn_IQconversion
    USE ENTITY work.phaseCorrectionCordic_src_fcn_IQconversion(rtl);

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL ab_mag                           : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL Complex_to_Magnitude_Angle_out2  : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL Complex_to_Magnitude_Angle_out2_signed : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL angleCordicBefore                : unsigned(20 DOWNTO 0);  -- ufix21_En21
  SIGNAL angleBias_unsigned               : unsigned(20 DOWNTO 0);  -- ufix21_En21
  SIGNAL angleCordic                      : unsigned(20 DOWNTO 0);  -- ufix21_En21
  SIGNAL aNormalized                      : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL bNormalized                      : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL inphaseOutCordic                 : std_logic_vector(34 DOWNTO 0);  -- ufix35
  SIGNAL quadratureOutCordic              : std_logic_vector(34 DOWNTO 0);  -- ufix35
  SIGNAL aInConv                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL bInConv                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL inphaseIn_signed                 : signed(15 DOWNTO 0);  -- int16
  SIGNAL quadratureIn_signed              : signed(15 DOWNTO 0);  -- int16

BEGIN
  u_Complex_to_Magnitude_Angle : phaseCorrectionCordic_src_HDL_CMA_core
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In_re => a,  -- sfix18
              In_im => b,  -- sfix18
              validIn => Constant_out1,
              magnitude => ab_mag,  -- sfix19
              angle => Complex_to_Magnitude_Angle_out2  -- sfix21_En20
              );

  u_Cosine_HDL_Optimized : phaseCorrectionCordic_src_Cosine_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              u => std_logic_vector(angleCordic),  -- ufix21_En21
              x => aNormalized  -- sfix18_En16
              );

  u_Sine_HDL_Optimized : phaseCorrectionCordic_src_Sine_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              u => std_logic_vector(angleCordic),  -- ufix21_En21
              x => bNormalized  -- sfix18_En16
              );

  u_Subsystem1 : phaseCorrectionCordic_src_Subsystem1
    PORT MAP( inPhaseIn => inphaseIn,  -- int16
              quadratureIn => quadratureIn,  -- int16
              aNormalized => aNormalized,  -- sfix18_En16
              bNormalized => bNormalized,  -- sfix18_En16
              inphaseOut => inphaseOutCordic,  -- sfix35_En16
              quadratureOut => quadratureOutCordic  -- sfix35_En16
              );

  u_fcn_IQconversion : phaseCorrectionCordic_src_fcn_IQconversion
    PORT MAP( aIn => inphaseOutCordic,  -- sfix35_En16
              bIn => quadratureOutCordic,  -- sfix35_En16
              aInConv => aInConv,  -- int16
              bInConv => bInConv  -- int16
              );

  Constant_out1 <= '1';

  Complex_to_Magnitude_Angle_out2_signed <= signed(Complex_to_Magnitude_Angle_out2);

  angleCordicBefore <= unsigned(Complex_to_Magnitude_Angle_out2_signed);

  angleBias_unsigned <= unsigned(angleBias);

  angleCordic <= angleCordicBefore + angleBias_unsigned;

  ce_out <= clk_enable;

  inphaseOut <= aInConv;

  quadratureOut <= bInConv;

  magnitudeXcorr <= ab_mag;

END rtl;

