-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_dut.vhd
-- Created: 2025-02-23 12:06:09
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_dut
-- Source Path: phaseCorrectionCordic/phaseCorrectionCordic_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY phaseCorrectionCordic_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        a                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        b                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        inphaseIn                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        quadratureIn                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        angleBias                         :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21_En21
        ce_out                            :   OUT   std_logic;  -- ufix1
        inphaseOut                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        quadratureOut                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        magnitudeXcorr                    :   OUT   std_logic_vector(18 DOWNTO 0)  -- sfix19
        );
END phaseCorrectionCordic_dut;


ARCHITECTURE rtl OF phaseCorrectionCordic_dut IS

  -- Component Declarations
  COMPONENT phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          a                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          b                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          inphaseIn                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          quadratureIn                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          angleBias                       :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21_En21
          ce_out                          :   OUT   std_logic;  -- ufix1
          inphaseOut                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          quadratureOut                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          magnitudeXcorr                  :   OUT   std_logic_vector(18 DOWNTO 0)  -- sfix19
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT
    USE ENTITY work.phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL inphaseOut_sig                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL quadratureOut_sig                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL magnitudeXcorr_sig               : std_logic_vector(18 DOWNTO 0);  -- ufix19

BEGIN
  u_phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT : phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              a => a,  -- sfix18
              b => b,  -- sfix18
              inphaseIn => inphaseIn,  -- sfix16
              quadratureIn => quadratureIn,  -- sfix16
              angleBias => angleBias,  -- ufix21_En21
              ce_out => ce_out_sig,  -- ufix1
              inphaseOut => inphaseOut_sig,  -- sfix16
              quadratureOut => quadratureOut_sig,  -- sfix16
              magnitudeXcorr => magnitudeXcorr_sig  -- sfix19
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  inphaseOut <= inphaseOut_sig;

  quadratureOut <= quadratureOut_sig;

  magnitudeXcorr <= magnitudeXcorr_sig;

END rtl;

