-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT_pkg.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT_pkg IS
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE vector_of_signed18 IS ARRAY (NATURAL RANGE <>) OF signed(17 DOWNTO 0);
  TYPE vector_of_unsigned5 IS ARRAY (NATURAL RANGE <>) OF unsigned(4 DOWNTO 0);
END phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT_pkg;

