-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_Quadrant_Correction.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_src_Quadrant_Correction
-- Source Path: phaseCorrectionCordic/Phase Correction Cordic IP DUT/HDL_CMA_core/Quadrant_Correction
-- Hierarchy Level: 2
-- Model version: 8.574
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY phaseCorrectionCordic_src_Quadrant_Correction IS
  PORT( zin                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En20
        QA_Control                        :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        zout                              :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En20
        );
END phaseCorrectionCordic_src_Quadrant_Correction;


ARCHITECTURE rtl OF phaseCorrectionCordic_src_Quadrant_Correction IS

  -- Signals
  SIGNAL QA_Control_unsigned              : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL yZeroXPositive                   : std_logic;  -- ufix1
  SIGNAL yZeroXNegative                   : std_logic;  -- ufix1
  SIGNAL xyNegative                       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL AbsRel                           : std_logic;  -- ufix1
  SIGNAL pidivtwo                         : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL zin_signed                       : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL pivdivtwosubout                  : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL mux1out                          : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL Negation_cast                    : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Negation_cast_1                  : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Negation_cast_2                  : signed(22 DOWNTO 0);  -- sfix23_En20
  SIGNAL mux1out_negate                   : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL pionepos                         : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL pi_subtraction                   : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL pioneneg                         : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL negpi_addition                   : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL mux2out                          : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL mux5out                          : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL zero                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL mux6out                          : signed(20 DOWNTO 0);  -- sfix21_En20

BEGIN
  QA_Control_unsigned <= unsigned(QA_Control);

  yZeroXPositive <= QA_Control_unsigned(4);

  yZeroXNegative <= QA_Control_unsigned(3);

  xyNegative <= QA_Control_unsigned(1 DOWNTO 0);

  AbsRel <= QA_Control_unsigned(2);

  pidivtwo <= to_signed(16#080000#, 21);

  zin_signed <= signed(zin);

  pivdivtwosubout <= pidivtwo - zin_signed;

  
  mux1out <= pivdivtwosubout WHEN AbsRel = '0' ELSE
      zin_signed;

  Negation_cast <= resize(mux1out, 22);
  Negation_cast_1 <=  - (Negation_cast);
  Negation_cast_2 <= resize(Negation_cast_1, 23);
  mux1out_negate <= Negation_cast_2(20 DOWNTO 0);

  pionepos <= to_signed(16#0FFFFF#, 21);

  pi_subtraction <= pionepos - mux1out;

  pioneneg <= to_signed(-16#100000#, 21);

  negpi_addition <= pioneneg + mux1out;

  
  mux2out <= mux1out WHEN xyNegative = to_unsigned(16#0#, 2) ELSE
      mux1out_negate WHEN xyNegative = to_unsigned(16#1#, 2) ELSE
      pi_subtraction WHEN xyNegative = to_unsigned(16#2#, 2) ELSE
      negpi_addition;

  
  mux5out <= mux2out WHEN yZeroXNegative = '0' ELSE
      pionepos;

  zero <= to_signed(16#000000#, 21);

  
  mux6out <= mux5out WHEN yZeroXPositive = '0' ELSE
      zero;

  zout <= std_logic_vector(mux6out);

END rtl;

