-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_Quadrant_Mapper.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_src_Quadrant_Mapper
-- Source Path: phaseCorrectionCordic/Phase Correction Cordic IP DUT/HDL_CMA_core/Quadrant_Mapper
-- Hierarchy Level: 2
-- Model version: 8.574
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY phaseCorrectionCordic_src_Quadrant_Mapper IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        xin                               :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
        yin                               :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
        xout                              :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        yout                              :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        QA_Control                        :   OUT   std_logic_vector(4 DOWNTO 0)  -- ufix5
        );
END phaseCorrectionCordic_src_Quadrant_Mapper;


ARCHITECTURE rtl OF phaseCorrectionCordic_src_Quadrant_Mapper IS

  -- Signals
  SIGNAL xin_signed                       : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL abs_rsvd_y                       : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL xAbs                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xAbsReg                          : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin_signed                       : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL abs_rsvd_y_1                     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL yAbs                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yAbsReg                          : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL XGreaterThanY                    : std_logic;  -- ufix1
  SIGNAL xout_1                           : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout_1                           : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL in2reg                           : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yZero                            : std_logic;  -- ufix1
  SIGNAL in1reg                           : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xPositive                        : std_logic;  -- ufix1
  SIGNAL yZeroXPositive                   : std_logic;  -- ufix1
  SIGNAL xNegative                        : std_logic;  -- ufix1
  SIGNAL yZeroXNegative                   : std_logic;  -- ufix1
  SIGNAL yNegative                        : std_logic;  -- ufix1
  SIGNAL qcControl                        : unsigned(4 DOWNTO 0);  -- ufix5

BEGIN
  xin_signed <= signed(xin);

  
  abs_rsvd_y <=  - (resize(xin_signed, 20)) WHEN xin_signed < to_signed(16#00000#, 19) ELSE
      resize(xin_signed, 20);
  xAbs <= abs_rsvd_y(18 DOWNTO 0);

  DelayxAbs_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xAbsReg <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xAbsReg <= xAbs;
      END IF;
    END IF;
  END PROCESS DelayxAbs_process;


  yin_signed <= signed(yin);

  
  abs_rsvd_y_1 <=  - (resize(yin_signed, 20)) WHEN yin_signed < to_signed(16#00000#, 19) ELSE
      resize(yin_signed, 20);
  yAbs <= abs_rsvd_y_1(18 DOWNTO 0);

  DelayyAbs_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yAbsReg <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yAbsReg <= yAbs;
      END IF;
    END IF;
  END PROCESS DelayyAbs_process;


  
  XGreaterThanY <= '1' WHEN xAbsReg > yAbsReg ELSE
      '0';

  
  xout_1 <= yAbsReg WHEN XGreaterThanY = '0' ELSE
      xAbsReg;

  xout <= std_logic_vector(xout_1);

  
  yout_1 <= xAbsReg WHEN XGreaterThanY = '0' ELSE
      yAbsReg;

  yout <= std_logic_vector(yout_1);

  Delayin2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      in2reg <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        in2reg <= yin_signed;
      END IF;
    END IF;
  END PROCESS Delayin2_process;


  
  yZero <= '1' WHEN in2reg = to_signed(16#00000#, 19) ELSE
      '0';

  Delayin1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      in1reg <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        in1reg <= xin_signed;
      END IF;
    END IF;
  END PROCESS Delayin1_process;


  
  xPositive <= '1' WHEN in1reg >= to_signed(16#00000#, 19) ELSE
      '0';

  yZeroXPositive <= yZero AND xPositive;

  
  xNegative <= '1' WHEN in1reg < to_signed(16#00000#, 19) ELSE
      '0';

  yZeroXNegative <= yZero AND xNegative;

  
  yNegative <= '1' WHEN in2reg < to_signed(16#00000#, 19) ELSE
      '0';

  qcControl <= unsigned'(yZeroXPositive & yZeroXNegative & XGreaterThanY & xNegative & yNegative);

  QA_Control <= std_logic_vector(qcControl);

END rtl;

