-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_HDL_CMA_core.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_src_HDL_CMA_core
-- Source Path: phaseCorrectionCordic/Phase Correction Cordic IP DUT/HDL_CMA_core
-- Hierarchy Level: 1
-- Model version: 8.574
-- 
-- Complex to Magnitude-Angle
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT_pkg.ALL;

ENTITY phaseCorrectionCordic_src_HDL_CMA_core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In_re                             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        In_im                             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        validIn                           :   IN    std_logic;
        magnitude                         :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        angle                             :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En20
        );
END phaseCorrectionCordic_src_HDL_CMA_core;


ARCHITECTURE rtl OF phaseCorrectionCordic_src_HDL_CMA_core IS

  -- Component Declarations
  COMPONENT phaseCorrectionCordic_src_Quadrant_Mapper
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          xin                             :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
          yin                             :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
          xout                            :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
          yout                            :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
          QA_Control                      :   OUT   std_logic_vector(4 DOWNTO 0)  -- ufix5
          );
  END COMPONENT;

  COMPONENT phaseCorrectionCordic_src_CordicKernelMag
    PORT( xin                             :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
          yin                             :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
          zin                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En20
          lut_value                       :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En20
          idx                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          xout                            :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
          yout                            :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
          zout                            :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En20
          );
  END COMPONENT;

  COMPONENT phaseCorrectionCordic_src_Quadrant_Correction
    PORT( zin                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En20
          QA_Control                      :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          zout                            :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En20
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : phaseCorrectionCordic_src_Quadrant_Mapper
    USE ENTITY work.phaseCorrectionCordic_src_Quadrant_Mapper(rtl);

  FOR ALL : phaseCorrectionCordic_src_CordicKernelMag
    USE ENTITY work.phaseCorrectionCordic_src_CordicKernelMag(rtl);

  FOR ALL : phaseCorrectionCordic_src_Quadrant_Correction
    USE ENTITY work.phaseCorrectionCordic_src_Quadrant_Correction(rtl);

  -- Signals
  SIGNAL Delay_ValidIn_reg                : std_logic_vector(10 DOWNTO 0);  -- ufix1 [11]
  SIGNAL ValidOutDelayed                  : std_logic;
  SIGNAL reset_outval                     : std_logic;
  SIGNAL In_re_signed                     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL In_im_signed                     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL qMapReal                         : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL qMapImag                         : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL In1Register                      : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL In2Register                      : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL XQMapped                         : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yQMapped                         : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL ControlQC                        : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL XQMapped_signed                  : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yQMapped_signed                  : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xin1                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin1                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin1                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value1                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift1                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout1                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout1                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout1                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout1_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout1_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout1_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL xin2                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin2                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin2                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value2                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift2                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout2                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout2                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout2                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout2_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout2_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout2_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL xin3                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin3                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin3                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value3                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift3                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout3                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout3                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout3                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout3_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout3_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout3_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL xin4                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin4                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin4                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value4                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift4                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout4                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout4                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout4                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout4_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout4_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout4_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL xin5                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin5                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin5                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value5                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift5                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout5                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout5                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout5                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout5_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout5_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout5_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL xin6                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin6                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin6                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value6                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift6                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout6                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout6                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout6                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout6_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout6_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout6_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL xin7                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin7                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin7                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value7                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift7                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout7                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout7                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout7                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout7_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yout7_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout7_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL xin8                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL yin8                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zin8                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL lut_value8                       : unsigned(17 DOWNTO 0);  -- ufix18_En20
  SIGNAL shift8                           : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL xout8                            : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL yout8deadOut                     : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL zout8                            : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL xout8_signed                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xin9                             : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL CSD_Gain_Factor_mul_temp         : signed(34 DOWNTO 0);  -- sfix35_En15
  SIGNAL CSD_Gain_Factor_cast             : signed(33 DOWNTO 0);  -- sfix34_En15
  SIGNAL xoutscaled                       : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zeroC                            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL outSwitchMag                     : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL xin10                            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL zout8_signed                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL ControlQC_unsigned               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL zin9                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL DelayQC_Control_reg              : vector_of_unsigned5(0 TO 8);  -- ufix5 [9]
  SIGNAL ControlQCDelay                   : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL zout_corrected                   : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL zout_corrected_signed            : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL zeroCA                           : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL outSwitchAng                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL zout_corrected_1                 : signed(20 DOWNTO 0);  -- sfix21_En20

BEGIN
  u_QuadrantMapper : phaseCorrectionCordic_src_Quadrant_Mapper
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              xin => std_logic_vector(In1Register),  -- sfix19
              yin => std_logic_vector(In2Register),  -- sfix19
              xout => XQMapped,  -- sfix19
              yout => yQMapped,  -- sfix19
              QA_Control => ControlQC  -- ufix5
              );

  u_Iteration : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin1),  -- sfix19
              yin => std_logic_vector(yin1),  -- sfix19
              zin => std_logic_vector(zin1),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value1),  -- ufix18_En20
              idx => std_logic_vector(shift1),  -- ufix4
              xout => xout1,  -- sfix19
              yout => yout1,  -- sfix19
              zout => zout1  -- sfix21_En20
              );

  u_Iteration_1 : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin2),  -- sfix19
              yin => std_logic_vector(yin2),  -- sfix19
              zin => std_logic_vector(zin2),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value2),  -- ufix18_En20
              idx => std_logic_vector(shift2),  -- ufix4
              xout => xout2,  -- sfix19
              yout => yout2,  -- sfix19
              zout => zout2  -- sfix21_En20
              );

  u_Iteration_2 : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin3),  -- sfix19
              yin => std_logic_vector(yin3),  -- sfix19
              zin => std_logic_vector(zin3),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value3),  -- ufix18_En20
              idx => std_logic_vector(shift3),  -- ufix4
              xout => xout3,  -- sfix19
              yout => yout3,  -- sfix19
              zout => zout3  -- sfix21_En20
              );

  u_Iteration_3 : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin4),  -- sfix19
              yin => std_logic_vector(yin4),  -- sfix19
              zin => std_logic_vector(zin4),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value4),  -- ufix18_En20
              idx => std_logic_vector(shift4),  -- ufix4
              xout => xout4,  -- sfix19
              yout => yout4,  -- sfix19
              zout => zout4  -- sfix21_En20
              );

  u_Iteration_4 : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin5),  -- sfix19
              yin => std_logic_vector(yin5),  -- sfix19
              zin => std_logic_vector(zin5),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value5),  -- ufix18_En20
              idx => std_logic_vector(shift5),  -- ufix4
              xout => xout5,  -- sfix19
              yout => yout5,  -- sfix19
              zout => zout5  -- sfix21_En20
              );

  u_Iteration_5 : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin6),  -- sfix19
              yin => std_logic_vector(yin6),  -- sfix19
              zin => std_logic_vector(zin6),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value6),  -- ufix18_En20
              idx => std_logic_vector(shift6),  -- ufix4
              xout => xout6,  -- sfix19
              yout => yout6,  -- sfix19
              zout => zout6  -- sfix21_En20
              );

  u_Iteration_6 : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin7),  -- sfix19
              yin => std_logic_vector(yin7),  -- sfix19
              zin => std_logic_vector(zin7),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value7),  -- ufix18_En20
              idx => std_logic_vector(shift7),  -- ufix4
              xout => xout7,  -- sfix19
              yout => yout7,  -- sfix19
              zout => zout7  -- sfix21_En20
              );

  u_Iteration_7 : phaseCorrectionCordic_src_CordicKernelMag
    PORT MAP( xin => std_logic_vector(xin8),  -- sfix19
              yin => std_logic_vector(yin8),  -- sfix19
              zin => std_logic_vector(zin8),  -- sfix21_En20
              lut_value => std_logic_vector(lut_value8),  -- ufix18_En20
              idx => std_logic_vector(shift8),  -- ufix4
              xout => xout8,  -- sfix19
              yout => yout8deadOut,  -- sfix19
              zout => zout8  -- sfix21_En20
              );

  u_QuadrantCorrection : phaseCorrectionCordic_src_Quadrant_Correction
    PORT MAP( zin => std_logic_vector(zin9),  -- sfix21_En20
              QA_Control => std_logic_vector(ControlQCDelay),  -- ufix5
              zout => zout_corrected  -- sfix21_En20
              );

  Delay_ValidIn_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_ValidIn_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_ValidIn_reg(0) <= validIn;
        Delay_ValidIn_reg(10 DOWNTO 1) <= Delay_ValidIn_reg(9 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay_ValidIn_process;

  ValidOutDelayed <= Delay_ValidIn_reg(10);

  reset_outval <=  NOT ValidOutDelayed;

  In_re_signed <= signed(In_re);

  qMapReal <= resize(In_re_signed, 19);

  In_im_signed <= signed(In_im);

  qMapImag <= resize(In_im_signed, 19);

  DelayRealInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In1Register <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In1Register <= qMapReal;
      END IF;
    END IF;
  END PROCESS DelayRealInput_process;


  DelayImagInput_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In2Register <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        In2Register <= qMapImag;
      END IF;
    END IF;
  END PROCESS DelayImagInput_process;


  XQMapped_signed <= signed(XQMapped);

  yQMapped_signed <= signed(yQMapped);

  DelayQuadMapper1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin1 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin1 <= XQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper1_process;


  DelayQuadMapper2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin1 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin1 <= yQMapped_signed;
      END IF;
    END IF;
  END PROCESS DelayQuadMapper2_process;


  zin1 <= to_signed(16#000000#, 21);

  lut_value1 <= to_unsigned(16#25C81#, 18);

  shift1 <= to_unsigned(16#1#, 4);

  xout1_signed <= signed(xout1);

  yout1_signed <= signed(yout1);

  zout1_signed <= signed(zout1);

  Pipeline1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin2 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin2 <= xout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_process;


  Pipeline1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin2 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin2 <= yout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_1_process;


  Pipeline1_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin2 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin2 <= zout1_signed;
      END IF;
    END IF;
  END PROCESS Pipeline1_2_process;


  lut_value2 <= to_unsigned(16#13F67#, 18);

  shift2 <= to_unsigned(16#2#, 4);

  xout2_signed <= signed(xout2);

  yout2_signed <= signed(yout2);

  zout2_signed <= signed(zout2);

  Pipeline2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin3 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin3 <= xout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_process;


  Pipeline2_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin3 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin3 <= yout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_1_process;


  Pipeline2_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin3 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin3 <= zout2_signed;
      END IF;
    END IF;
  END PROCESS Pipeline2_2_process;


  lut_value3 <= to_unsigned(16#0A222#, 18);

  shift3 <= to_unsigned(16#3#, 4);

  xout3_signed <= signed(xout3);

  yout3_signed <= signed(yout3);

  zout3_signed <= signed(zout3);

  Pipeline3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin4 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin4 <= xout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_process;


  Pipeline3_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin4 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin4 <= yout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_1_process;


  Pipeline3_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin4 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin4 <= zout3_signed;
      END IF;
    END IF;
  END PROCESS Pipeline3_2_process;


  lut_value4 <= to_unsigned(16#05162#, 18);

  shift4 <= to_unsigned(16#4#, 4);

  xout4_signed <= signed(xout4);

  yout4_signed <= signed(yout4);

  zout4_signed <= signed(zout4);

  Pipeline4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin5 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin5 <= xout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_process;


  Pipeline4_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin5 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin5 <= yout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_1_process;


  Pipeline4_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin5 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin5 <= zout4_signed;
      END IF;
    END IF;
  END PROCESS Pipeline4_2_process;


  lut_value5 <= to_unsigned(16#028BB#, 18);

  shift5 <= to_unsigned(16#5#, 4);

  xout5_signed <= signed(xout5);

  yout5_signed <= signed(yout5);

  zout5_signed <= signed(zout5);

  Pipeline5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin6 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin6 <= xout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_process;


  Pipeline5_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin6 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin6 <= yout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_1_process;


  Pipeline5_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin6 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin6 <= zout5_signed;
      END IF;
    END IF;
  END PROCESS Pipeline5_2_process;


  lut_value6 <= to_unsigned(16#0145F#, 18);

  shift6 <= to_unsigned(16#6#, 4);

  xout6_signed <= signed(xout6);

  yout6_signed <= signed(yout6);

  zout6_signed <= signed(zout6);

  Pipeline6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin7 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin7 <= xout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_process;


  Pipeline6_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin7 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin7 <= yout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_1_process;


  Pipeline6_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin7 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin7 <= zout6_signed;
      END IF;
    END IF;
  END PROCESS Pipeline6_2_process;


  lut_value7 <= to_unsigned(16#00A30#, 18);

  shift7 <= to_unsigned(16#7#, 4);

  xout7_signed <= signed(xout7);

  yout7_signed <= signed(yout7);

  zout7_signed <= signed(zout7);

  Pipeline7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin8 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin8 <= xout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_process;


  Pipeline7_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      yin8 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        yin8 <= yout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_1_process;


  Pipeline7_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin8 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin8 <= zout7_signed;
      END IF;
    END IF;
  END PROCESS Pipeline7_2_process;


  lut_value8 <= to_unsigned(16#00518#, 18);

  shift8 <= to_unsigned(16#8#, 4);

  xout8_signed <= signed(xout8);

  Pipeline8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin9 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin9 <= xout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_process;


  -- CSD Encoding (28141) : 1001'001'00001'01'01; Cost (Adders) = 5
  CSD_Gain_Factor_mul_temp <= ((((resize(xin9 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 35) - resize(xin9 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 35)) - resize(xin9 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 35)) - resize(xin9 & '0' & '0' & '0' & '0', 35)) - resize(xin9 & '0' & '0', 35)) + resize(xin9, 35);
  CSD_Gain_Factor_cast <= CSD_Gain_Factor_mul_temp(33 DOWNTO 0);
  xoutscaled <= CSD_Gain_Factor_cast(33 DOWNTO 15);

  zeroC <= to_signed(16#00000#, 19);

  
  outSwitchMag <= xoutscaled WHEN reset_outval = '0' ELSE
      zeroC;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xin10 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xin10 <= outSwitchMag;
      END IF;
    END IF;
  END PROCESS Output_Register_process;


  magnitude <= std_logic_vector(xin10);

  zout8_signed <= signed(zout8);

  ControlQC_unsigned <= unsigned(ControlQC);

  Pipeline8_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zin9 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zin9 <= zout8_signed;
      END IF;
    END IF;
  END PROCESS Pipeline8_1_process;


  DelayQC_Control_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      DelayQC_Control_reg <= (OTHERS => to_unsigned(16#00#, 5));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        DelayQC_Control_reg(0) <= ControlQC_unsigned;
        DelayQC_Control_reg(1 TO 8) <= DelayQC_Control_reg(0 TO 7);
      END IF;
    END IF;
  END PROCESS DelayQC_Control_process;

  ControlQCDelay <= DelayQC_Control_reg(8);

  zout_corrected_signed <= signed(zout_corrected);

  zeroCA <= to_signed(16#000000#, 21);

  
  outSwitchAng <= zout_corrected_signed WHEN reset_outval = '0' ELSE
      zeroCA;

  Output_Register_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      zout_corrected_1 <= to_signed(16#000000#, 21);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        zout_corrected_1 <= outSwitchAng;
      END IF;
    END IF;
  END PROCESS Output_Register_1_process;


  angle <= std_logic_vector(zout_corrected_1);

END rtl;

