-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\phaseCorrectionCordic\phaseCorrectionCordic_src_Sine_HDL_Optimized.vhd
-- Created: 2025-02-23 12:06:03
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: phaseCorrectionCordic_src_Sine_HDL_Optimized
-- Source Path: phaseCorrectionCordic/Phase Correction Cordic IP DUT/Sine HDL Optimized
-- Hierarchy Level: 1
-- Model version: 8.574
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.phaseCorrectionCordic_src_Phase_Correction_Cordic_IP_DUT_pkg.ALL;

ENTITY phaseCorrectionCordic_src_Sine_HDL_Optimized IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic_vector(20 DOWNTO 0);  -- ufix21_En21
        x                                 :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En16
        );
END phaseCorrectionCordic_src_Sine_HDL_Optimized;


ARCHITECTURE rtl OF phaseCorrectionCordic_src_Sine_HDL_Optimized IS

  -- Constants
  CONSTANT Look_Up_Table_data             : vector_of_signed18(0 TO 63) := 
    (to_signed(16#00000#, 18), to_signed(16#00648#, 18), to_signed(16#00C90#, 18), to_signed(16#012D5#, 18),
     to_signed(16#01918#, 18), to_signed(16#01F56#, 18), to_signed(16#02590#, 18), to_signed(16#02BC4#, 18),
     to_signed(16#031F1#, 18), to_signed(16#03817#, 18), to_signed(16#03E34#, 18), to_signed(16#04447#, 18),
     to_signed(16#04A50#, 18), to_signed(16#0504D#, 18), to_signed(16#0563E#, 18), to_signed(16#05C22#, 18),
     to_signed(16#061F8#, 18), to_signed(16#067BE#, 18), to_signed(16#06D74#, 18), to_signed(16#0731A#, 18),
     to_signed(16#078AD#, 18), to_signed(16#07E2F#, 18), to_signed(16#0839C#, 18), to_signed(16#088F6#, 18),
     to_signed(16#08E3A#, 18), to_signed(16#09368#, 18), to_signed(16#09880#, 18), to_signed(16#09D80#, 18),
     to_signed(16#0A268#, 18), to_signed(16#0A736#, 18), to_signed(16#0ABEB#, 18), to_signed(16#0B086#, 18),
     to_signed(16#0B505#, 18), to_signed(16#0B968#, 18), to_signed(16#0BDAF#, 18), to_signed(16#0C1D8#, 18),
     to_signed(16#0C5E4#, 18), to_signed(16#0C9D1#, 18), to_signed(16#0CD9F#, 18), to_signed(16#0D14D#, 18),
     to_signed(16#0D4DB#, 18), to_signed(16#0D848#, 18), to_signed(16#0DB94#, 18), to_signed(16#0DEBE#, 18),
     to_signed(16#0E1C6#, 18), to_signed(16#0E4AA#, 18), to_signed(16#0E76C#, 18), to_signed(16#0EA0A#, 18),
     to_signed(16#0EC83#, 18), to_signed(16#0EED9#, 18), to_signed(16#0F109#, 18), to_signed(16#0F314#, 18),
     to_signed(16#0F4FA#, 18), to_signed(16#0F6BA#, 18), to_signed(16#0F854#, 18), to_signed(16#0F9C8#, 18),
     to_signed(16#0FB15#, 18), to_signed(16#0FC3B#, 18), to_signed(16#0FD3B#, 18), to_signed(16#0FE13#, 18),
     to_signed(16#0FEC4#, 18), to_signed(16#0FF4E#, 18), to_signed(16#0FFB1#, 18), to_signed(16#0FFEC#, 18));  -- sfix18 [64]

  -- Signals
  SIGNAL u_unsigned                       : unsigned(20 DOWNTO 0);  -- ufix21_En21
  SIGNAL insig_out1                       : unsigned(7 DOWNTO 0);  -- ufix8_En8
  SIGNAL Point50_out1                     : unsigned(17 DOWNTO 0);  -- ufix18_En18
  SIGNAL LTEp50_cast                      : unsigned(17 DOWNTO 0);  -- ufix18_En18
  SIGNAL LTEp50_out1                      : std_logic;
  SIGNAL RAMDelayBalance_out1             : std_logic;
  SIGNAL pow2switch_out1                  : std_logic;
  SIGNAL Amp50_sub_cast                   : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL Amp50_sub_cast_1                 : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL Amp50_out1                       : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL insig_out1_dtc                   : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL QuadHandle1_out1                 : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL Point25_out1                     : unsigned(17 DOWNTO 0);  -- ufix18_En18
  SIGNAL LTEp25_cast                      : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL LTEp25_out1                      : std_logic;
  SIGNAL p50mA_sub_cast                   : signed(19 DOWNTO 0);  -- sfix20_En18
  SIGNAL p50mA_sub_cast_1                 : signed(19 DOWNTO 0);  -- sfix20_En18
  SIGNAL p50mA_out1                       : signed(19 DOWNTO 0);  -- sfix20_En18
  SIGNAL p50mA_out1_dtc                   : unsigned(7 DOWNTO 0);  -- ufix8_En8
  SIGNAL QuadHandle1_out1_dtc             : unsigned(7 DOWNTO 0);  -- ufix8_En8
  SIGNAL QuadHandle2_out1                 : unsigned(7 DOWNTO 0);  -- ufix8_En8
  SIGNAL CastU16En2_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL CastU16En4_out1                  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL CastU16En3_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Saturation_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL prelookup_idx                    : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Look_Up_Table_out1               : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Unit_Delay_out1                  : signed(17 DOWNTO 0) := to_signed(16#00000#, 18);  -- sfix18_En16
  SIGNAL Negate_cast                      : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL Negate_cast_1                    : signed(18 DOWNTO 0);  -- sfix19_En16
  SIGNAL Negate_out1                      : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Sine                             : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Sine_1                           : signed(17 DOWNTO 0);  -- sfix18_En16

BEGIN
  -- (C) 2016 Mathworks, Inc

  u_unsigned <= unsigned(u);

  insig_out1 <= u_unsigned(20 DOWNTO 13);

  Point50_out1 <= to_unsigned(16#20000#, 18);

  LTEp50_cast <= insig_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  
  LTEp50_out1 <= '1' WHEN LTEp50_cast <= Point50_out1 ELSE
      '0';

  RAMDelayBalance_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      RAMDelayBalance_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        RAMDelayBalance_out1 <= LTEp50_out1;
      END IF;
    END IF;
  END PROCESS RAMDelayBalance_process;


  pow2switch_out1 <= '1';

  Amp50_sub_cast <= signed(resize(insig_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 19));
  Amp50_sub_cast_1 <= signed(resize(Point50_out1, 19));
  Amp50_out1 <= Amp50_sub_cast - Amp50_sub_cast_1;

  insig_out1_dtc <= signed(resize(insig_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 19));

  
  QuadHandle1_out1 <= Amp50_out1 WHEN LTEp50_out1 = '0' ELSE
      insig_out1_dtc;

  Point25_out1 <= to_unsigned(16#10000#, 18);

  LTEp25_cast <= signed(resize(Point25_out1, 19));
  
  LTEp25_out1 <= '1' WHEN QuadHandle1_out1 <= LTEp25_cast ELSE
      '0';

  p50mA_sub_cast <= signed(resize(Point50_out1, 20));
  p50mA_sub_cast_1 <= resize(QuadHandle1_out1, 20);
  p50mA_out1 <= p50mA_sub_cast - p50mA_sub_cast_1;

  p50mA_out1_dtc <= unsigned(p50mA_out1(17 DOWNTO 10));

  QuadHandle1_out1_dtc <= unsigned(QuadHandle1_out1(17 DOWNTO 10));

  
  QuadHandle2_out1 <= p50mA_out1_dtc WHEN LTEp25_out1 = '0' ELSE
      QuadHandle1_out1_dtc;

  CastU16En2_out1 <= QuadHandle2_out1;

  CastU16En4_out1 <= resize(CastU16En2_out1, 9);

  
  CastU16En3_out1 <= "11111111" WHEN CastU16En4_out1(8) /= '0' ELSE
      CastU16En4_out1(7 DOWNTO 0);

  -- saturation block maybe optimized away
  -- if the NumDataPoints is a power of 2
  
  Saturation_out1 <= to_unsigned(16#3F#, 8) WHEN CastU16En3_out1 > to_unsigned(16#3F#, 8) ELSE
      CastU16En3_out1;

  
  Switch_out1 <= CastU16En3_out1 WHEN pow2switch_out1 = '0' ELSE
      Saturation_out1;

  
  prelookup_idx <= to_unsigned(16#00#, 6) WHEN Switch_out1 = to_unsigned(16#00#, 8) ELSE
      to_unsigned(16#3F#, 6) WHEN Switch_out1 >= to_unsigned(16#3F#, 8) ELSE
      Switch_out1(5 DOWNTO 0);

  Look_Up_Table_out1 <= Look_Up_Table_data(to_integer(prelookup_idx));

  Unit_Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Look_Up_Table_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Negate_cast <= resize(Unit_Delay_out1, 19);
  Negate_cast_1 <=  - (Negate_cast);
  Negate_out1 <= Negate_cast_1(17 DOWNTO 0);

  
  Sine <= Negate_out1 WHEN RAMDelayBalance_out1 = '0' ELSE
      Unit_Delay_out1;

  Sine_1 <= Sine;

  x <= std_logic_vector(Sine_1);

END rtl;

